### ISSUE TITLE
call for interested people

### ISSUE THREAD

**Issue by KostyaSha** [KostyaSha/yet-another-docker-plugin#1]
I feel that some things can be still broken, i'm again at point when time to implement integration tests before release. As i'm working in parallel on docker-java development some mess in library related code may exist (some docker-java future code here or vice-versa).
There is lack of documentation, but i think interested in people will understand.

@hawky-4s- @lanwen hi, are you interested in testing?

**Comment by hawky-4s-** [comment]
Yes, I'll have a look at it. Thx for the invitation.
Am 07.12.2015 22:32 schrieb "Kanstantsin Shautsou" <notifications@github.com

**Comment by hawky-4s-** [comment]
What are the requirements atm? Does it work with Docker 1.8/1.9? Swarm 0.4.0/1.0?

**Comment by KostyaSha** [comment]
@hawky-4s- i actively working on docker-java changes need check what docker-java version i used :)
@hawky-4s- any docker version should work if you point api url to concrete version (yes, seems i found when this is useful), i will add this option back to connector.

For swarm will be glad to know results. As i understand it not fully supported by docker-java and swarm has it's own versions.  Documentation says `The Docker Swarm API is mostly compatible with the Docker Remote API.` while docker remote API has many versions so for what version data will be removed?

@hawky-4s- it may contain issues that you reported, but i will be glad to review them again on this clean code base. And while it not released i can refactor code if it will be required.

**Comment by hawky-4s-** [comment]
@menski: Just adding you to follow, because you are interested too.

**Comment by hawky-4s-** [comment]
@KostyaSha do you know how to create mock slaves or something like that for unit / it testing?

**Comment by KostyaSha** [comment]
@hawky-4s- i plan do Docker-inDocker to simulate different configurations.

**Comment by KostyaSha** [comment]
Btw @stephenc will it be the cleanest implementation of current bad cloud API? :) I also found inconsistency in Slave rename option and rw field that it provides via jelly (need to be reviewed and fixed in some way).

**Comment by KostyaSha** [comment]
> What are the prerequisites atm? Does it work with Docker 1.8/1.9? Swarm 0.4.0/1.0?

Docker-java update in #2 , opened https://github.com/docker-java/docker-java/issues/395 for  swarm overview in library.  @hawky-4s- as soon as somebody will help me with testing i will be able to make something good :)

**Comment by KostyaSha** [comment]
@pgokul (Don't want pollute docker-plugin with comments about this plugin). If you are interesting in credentials support you can try this plugin (should be available in experimental center). I continue development started in docker-plugin here. Or you can continue waiting such feature in docker-plugin.

**Comment by KostyaSha** [comment]
@ediri FYI https connection is supported here.

**Comment by pgokul** [comment]
@KostyaSha . Thanks for the invite. I will give it a try.

**Comment by KostyaSha** [comment]
@smiller171 FYI

**Comment by KostyaSha** [comment]
Released into main update center, feel free to try.

**Comment by KostyaSha** [comment]
@thomassuckow FYI

**Comment by KostyaSha** [comment]
@HadesArchitect FYI

**Comment by KostyaSha** [comment]
@eaglerainbow you may try this plugin as part of your issues were already solved.
