### ISSUE TITLE
Multiple clouds with same label, only first cloud will run.

### ISSUE THREAD

**Issue by rgrsoucy** [KostyaSha/yet-another-docker-plugin#106]
Running YADP 0.1.0-rc27.

I have 3 clouds configured. Each have the same template defined with the same label. Instead of round robin it always runs only the first cloud template.

I thought I saw a comment somewhere that the round robin or load balancing should work?

**Comment by KostyaSha** [comment]
I would suggest to use swarm. There is no load strategies between clouds and i have no real idea how to do it while there is swarm that is created for such things.

**Comment by fboudra** [comment]
@KostyaSha can you describe such setup in jenkins/y-a-d-p context? There's #54 but it seems to imply we can't actually use swarm with y-a-d-p.

**Comment by KostyaSha** [comment]
swarm api compatible with docker, you can use it now. There is no special features support now. Swarm is in my closest list after github-integration-plugin improvements.

**Comment by rgrsoucy** [comment]
@fboudra  if you run the docker swarm container, and follow the instructions to setup your swarm cluster. You can then point the YAD plugin api url to the swarm master and the swarm master will take care of the load balancing for you. One thing is that it has to be pre docker 1.12. The new version of docker that comes with built in swarm does not work this way (yet).

This is the one I used and got to work: https://hub.docker.com/_/swarm/

**Comment by tpeyrard** [comment]
@rgrsoucy I started a swarm image on port 4000. In the YAD plugin I set the docker url to the server:4000 and I can run containers. Unfortunately they all run on the "master", they are not load balanced on the cluster.
I use docker 1.12, but not the docker swarm mode.
I follower this tutorial to build by Swarm cluster: https://docs.docker.com/swarm/install-manual/
Did I miss something in the plugin configuration? Because it seems to run a container against the cluster, one need to set the command line to : `docker -H :4000 run jenkins-slave`. However, i guess the plugin just issue something like `docker run jenkins-slave`.
Is there a way to modify the command?
Thanks

**Comment by rgrsoucy** [comment]
It doesn't work in 1.12 because of API changes. You need to use the docker
swarm image from Docker. hub that I referenced above. The other option is
to reference the older API in the Jenkins plug-in when you set up the
plugin.

**Comment by tpeyrard** [comment]
@rgrsoucy Thanks for the details. I'll try it.

But with my current setup, I already get the correct (old) API:
```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Version@23dbb2c5[
  apiVersion=1.22
  arch=amd64
  gitCommit=27968ed
  goVersion=go1.5.4
  kernelVersion=4.4.0-28-generic
  operatingSystem=linux
  version=swarm/1.2.5
  buildTime=Thu Aug 18 23:10:29 UTC 2016
  experimental=<null>
]
```

The problem now, is that I can't pull the image of my jenkins-slave (a custom image on a private repository):
```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Pulling macpro.fr.murex.com:5000/rtdb/jenkins-slave:latest... : downloaded
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at com.github.kostyasha.yad.commons.DockerPullImage.exec(DockerPullImage.java:111)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:194)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

That's strange, because from all my docker nodes I can pull the image.

Is it related to API issue?

**Comment by rgrsoucy** [comment]
@tpeyrard 
I did have some issue's in the past having the plugin pull my images from the repo. Rather than spend time working and to move forward  I just pulled the images manually on each node and set the plugin to never pull. I believe the issue has to do with where your config.json (or whatever repo config you have) file lives when running the pull from jenkins.

**Comment by tpeyrard** [comment]
@rgrsoucy Perfect it works!
Thank you.

I'll try to make it work with my custom repository later.

**Comment by KostyaSha** [comment]
Pulling has something different for swarm! I'm working on swarm branch in docker-java library (but unfortunately busy with github-integration-plugin).

**Comment by Starefossen** [comment]
I kind of hoped I could have multiple Docker nodes with the same lable and yadp would round robbin between them...

**Comment by farahfa** [comment]
@rgrsoucy Do I need to consul for this? I've been trying to start a swarm using your instructions and the instructions found on [this page](https://hub.docker.com/_/swarm/), but I can't seem to get it to work.. I'm on docker version 1.11.2...

**Comment by dsmorse** [comment]
I just want to make sure I understand the current state of the problem.  YADP doesn't do any load balancing (yet as I see PR #167 has recently been submitted).  The proposed solution on this thread was to use swarm but it has to be a pre 1.12 version.  Has any progress been made on a newer version of swarm? I tried to use swarm but had problems with the master attempting to ssh to the private IP of the container vs the docker engine IP, does leveraging swarm for load balancing require JNLP to avoid this?

**Comment by samrocketman** [comment]
From what I learned researching and writing #167.  [`hudson.slaves.NodeProvisioner.update()`](https://github.com/jenkinsci/jenkins/blob/jenkins-2.42/core/src/main/java/hudson/slaves/NodeProvisioner.java#L320) calls [`DockerProvisioningStrategy.apply()`](https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/DockerProvisioningStrategy.java#L56) which returns `NodeProvisioner.StrategyDecision` (a decision of how it's going to provision the agents and on which clouds).  So the logic is left up to apply() to do the right thing with how it provisions across the configured clouds.  I've tested it with 15 clouds configured locally (really just duplicating the config but interacting with the same local cloud).  It properly provisions as described and definitely improves if you have more clouds configured (unlike the current behavior which is less performance with more clouds configured).

All of the above can be verified by going to the Jenkins logger (Manage Jenkins > Logs) and adding log listeners for classes:

- hudson.slaves.NodeProvisioner
- com.github.kostyasha.yad.DockerProvisioningStrategy

**Comment by stobias123** [comment]
If you don't want to run swarm - Just generate a random number and pick your cloud.
```
nodes = ['docker','docker1']
choice=new Random().nextInt(2)
node(nodes[choice]){
    sh 'echo "my ip address is: $(curl 169.254.169.254/2016-09-02/meta-data/local-ipv4)"'
}
```
