### ISSUE TITLE
Warning when using JNLP-Launcher with Jenkins 2.30

### ISSUE THREAD

**Issue by olemartin** [KostyaSha/yet-another-docker-plugin#111]
I get this error when starting jenkins with "java -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true   -jar /usr/lib/jenkins/jenkins.war"

Without using disableStrictVerification I am not able to start slaves at all
```
Nov 14, 2016 12:43:01 PM jenkins.slaves.DefaultJnlpSlaveReceiver afterProperties
WARNING: Connecting hostname-3121e63c4ddd as a JNLP agent where the launcher class com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher does not mark itself correctly as being a JNLP agent.
```

**Comment by KostyaSha** [comment]
thanks, will check.

**Comment by oleg-nenashev** [comment]
Yes, it is as-designed (?) behavior in Jenkins 2.27. See [JENKINS-39232](https://issues.jenkins-ci.org/browse/JENKINS-39232), which was solved by adding such strict verification.

@KostyaSha in order to fix the issue, your Launcher should extend JNLPLauncher or core's filter/proxy class

**Comment by KostyaSha** [comment]
@oleg-nenashev i already have own class that i extend for JNLP and SSH launching.

**Comment by KostyaSha** [comment]
That looks like one more compatibility broken core change.

**Comment by olemartin** [comment]
Will you fix this?

**Comment by gschrader** [comment]
I think I'm hitting this issue as well. I get the `The server rejected the connection: None of the protocols were accepted` exception. I've been trying to use the latest jenkins LTS release but it looks like that version has the JNLP breaking change.

Does anyone recommend a Jenkins/YAD plugin version combo that works correctly?

**Comment by KostyaSha** [comment]
I think workaround is in master.  Will provide link to test hpi in one minute.

**Comment by KostyaSha** [comment]
https://jitpack.io/com/github/KostyaSha/yet-another-docker-plugin/yet-another-docker-plugin/07390d9/yet-another-docker-plugin-07390d9.hpi

**Comment by gschrader** [comment]
Thanks I will try this. I see I was also missing the ` -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true` my bad!

**Comment by KostyaSha** [comment]
With test hpi it shouldn't be required. If hpi  works for you i will run release tomorrow.

**Comment by gschrader** [comment]
It works, thank you very much!

**Comment by KostyaSha** [comment]
running release.
