### ISSUE TITLE
[feature request] ability to make cloud offline

### ISSUE THREAD

**Issue by fboudra** [KostyaSha/yet-another-docker-plugin#113]
A node can be marked temporary offline. It's a quite useful feature when the node is under maintenance.

It will be useful to have a similar feature to mark a cloud offline, when for example the docker server is under maintenance or can't be reached due to network problems.

Recently, one of our gateway was down and several docker servers were unreachable as a result. y-a-d was trying to reach them,  timeout and try again (wild guess). The observed side affect is that it delayed reaching the remaining docker servers and start slaves by +20min. If I had such feature, I could have marked the affected clouds offline and y-a-d would nicely ignored them until the problem is fixed.

**Comment by KostyaSha** [comment]
Well, i though it enough to set 0 instances...

**Comment by fboudra** [comment]
good point, I haven't thought about that :)

**Comment by rgrsoucy** [comment]
I will sometimes just rename the label so no new jobs will try and run the plugin.

**Comment by KostyaSha** [comment]
I hope it's enough to set 0 instances, so closing. If it has some issues, then checkbox or something else could be added.

**Comment by fboudra** [comment]
yes, thanks. It works fine.
