### ISSUE TITLE
[question] what's happening after "DOCKER_HOST variable" ?

### ISSUE THREAD

**Issue by fboudra** [KostyaSha/yet-another-docker-plugin#114]
What's happening for 40 minutes between "DOCKER_HOST variable" and "Injecting DOCKER_CONTAINER_ID variable" ?

```
00:14:21.083 [YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
00:14:21.083 [YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
00:14:21.083 [YAD-PLUGIN] DOCKER_HOST variable.
00:57:00.363 [YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
00:57:00.364 [YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
00:57:00.364 [YAD-PLUGIN] DOCKER_HOST variable.
00:57:00.365 Finished: SUCCESS
```

The build is finished, it took around 14 minutes. Then it seems we're in YAD but my assumption could be wrong since we observe only YAD output in the console.

**Comment by KostyaSha** [comment]
Wow, no idea... need check what code does it call. Only if something was locked. Could you make stracktrace during this delay?

**Comment by KostyaSha** [comment]
jenkins_url/threadDump

**Comment by fboudra** [comment]
Archiving artifacts is still running in the background. Nothing to do with YAD. It just appears that the output messages are async so we're under the impression it's an issue with YAD.

Thanks for the debug tip.
