### ISSUE TITLE
Registry Credentials drop down not picking up values

### ISSUE THREAD

**Issue by RobQuads** [KostyaSha/yet-another-docker-plugin#116]
I am trying to configure this plugin to pull from a registry which requires authentication. The "Registry Credentials" does not show any of the existing entries in the credentials section.

If I click on the "Add" button it lets me add credentials which can be found using the main menu but are  still not listed in the drop down.

Plugin v0.1.0-rc30
Jenkins ver. 2.7.4

**Comment by KostyaSha** [comment]
Please specify credentials-plugin version because it has bugs

**Comment by KostyaSha** [comment]
Please show screenshots because it may happen that you used wrong credentials type because credentials plugin doesn't allow to limit scopes/types during UI creation.

**Comment by RobQuads** [comment]
I currently have credentials-plugin 2.1.10

![credentials](https://cloud.githubusercontent.com/assets/2182970/20671289/ac03d0f4-b574-11e6-9330-e9deb09b40f8.png)

In the credentials section it lists lots of jenkins global credentials

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/commons/DockerPullImage.java#L103
is only supported type ATM.

Only cred type with such name https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/credentials/DockerRegistryAuthCredentials.java#L61 will be listed.

**Comment by RobQuads** [comment]
How do you add a Docker Registry Auth  - Is it using another plugin? The only option to create in my dropdown is Jenkins?

**Comment by KostyaSha** [comment]
No, this Auth type exists in this plugin and used by this plugin. Does it appear in dropdown if you create this type?

**Comment by dvskumar** [comment]
I too faced the same issue. Later I realized that I need to enable 'Docker Registry Auth' credentials type in Manage Jenkins --> Configure Credentials --> Types (only selected)

**Comment by KostyaSha** [comment]
Sound like new options from credentials plugin.. Could you show screenshot?

**Comment by dvskumar** [comment]
![image](https://user-images.githubusercontent.com/16233639/35768767-63644cf4-0927-11e8-98b3-029c715dd519.png)
