### ISSUE TITLE
Agents going offline during build

### ISSUE THREAD

**Issue by deepraut89** [KostyaSha/yet-another-docker-plugin#119]
I am facing sometimes build failures due to agent going offline midway. Currently I am using JNLP launcher and its easily making containers up and taking the builds. I am running continuous builds using this plugin however facing sometimes sudden build failures due to agent going offline. 
Plugin: 0.1.0-rc30
Jenkins: 2.19.4
Java-8

`09:43:04 Agent went offline during the build`
`09:43:04 ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@42824b4c[name=cloud-zeus-62428d7df075]`
`09:43:04 	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)`
`09:43:04 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:629)`
`09:43:04 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)`
`09:43:04 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)`
`09:43:04 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)`
`09:43:04 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)`
`09:43:04 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)`
`09:43:04 	at java.lang.Thread.run(Thread.java:745)`
`09:43:04 Caused by: java.io.IOException: Connection reset by peer`
`09:43:04 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)`
`09:43:04 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)`
`09:43:04 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)`
`09:43:04 	at sun.nio.ch.IOUtil.read(IOUtil.java:197)`
`09:43:04 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)`
`09:43:04 	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:137)`
`09:43:04 	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:310)`
`09:43:04 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)`
`09:43:04 	... 6 more`
`09:43:04 `
`09:43:04 Build step 'Execute shell' marked build as failure`
`09:43:04 FATAL: java.io.IOException: Backing channel is disconnected.`
`09:43:04 hudson.remoting.RemotingSystemException: java.io.IOException: Backing channel is disconnected.`
`09:43:04 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:268)`
`09:43:04 	at com.sun.proxy.$Proxy109.stop(Unknown Source)`
`09:43:04 	at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.tearDown(SSHAgentBuildWrapper.java:414)`
`09:43:04 	at hudson.model.Build$BuildExecution.doRun(Build.java:173)`
`09:43:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)`
`09:43:04 	at hudson.model.Run.execute(Run.java:1720)`
`09:43:04 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)`
`09:43:04 	at hudson.model.ResourceController.execute(ResourceController.java:98)`
`09:43:04 	at hudson.model.Executor.run(Executor.java:404)`
`09:43:04 Caused by: java.io.IOException: Backing channel is disconnected.`
`09:43:04 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:187)`
`09:43:04 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:252)`
`09:43:04 	... 8 more`
`09:43:04 Stop Docker Containers is waiting for a checkpoint on continuous-integration #3809`
`09:43:04 Stopping all containers`
`09:43:04 Started calculate disk usage of build`
`09:43:05 Finished Calculation of disk usage of build in 0 seconds`
`09:43:05 Finished: FAILURE`

**Comment by KostyaSha** [comment]
What timeout settings do you have in cloud settings docker connector?

**Comment by deepraut89** [comment]
Type of Connection: NETTY
Connect Timeout: <Blank>
Docker Once Retention Startegy  Idle timeout: 2

**Comment by deepraut89** [comment]
This is not happening regularly but once/twice in 10 20 builds.
Checked "docker logs" of exited container

`WARNING: Cannot use /home/jenkins/workspace/continuous-integration@tmp/ssh579430500502427371
 due to UNIX_PATH_MAX; falling back to system temp dir`
`Dec 26, 2016 5:15:27 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel channel`
`java.net.SocketException: Connection reset`
`        at java.net.SocketInputStream.read(SocketInputStream.java:209)`
`        at java.net.SocketInputStream.read(SocketInputStream.java:141)`
`        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)`
`        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)`
`        at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:86)`
`        at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)`
`        at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)`
`        at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)`
`        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)`
`        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)`

`Dec 26, 2016 5:15:27 PM hudson.remoting.jnlp.Main$CuiListener status`

**Comment by KostyaSha** [comment]
> WARNING: Cannot use /home/jenkins/workspace/continuous-integration@tmp/ssh579430500502427371
>  due to UNIX_PATH_MAX; falling back to system temp dir`

What container/env do you use?

**Comment by KostyaSha** [comment]
You can use 3 quotes to make multiline.

Config is missing connector part. But according to log it looks like JNLP communication fails. 
Try create freestyle job with `sleep 100` body and check result. This is no output build that should help understand whether it some socket read timeouts.

**Comment by deepraut89** [comment]
Thanks for your suggestions.
Cloud config:
``` 
      <connector>
        <serverUrl>tcp://10.10.10.10:4243</serverUrl>
        <apiVersion>1.24</apiVersion>
        <credentialsId></credentialsId>
        <connectorType>NETTY</connectorType>
      </connector>
```
`docker logs` warning `due to UNIX_PATH_MAX; falling back to system temp dir` I figured out it is due to the ssh-agent enabled in my job and it has long job name. I am not sure whether it is as issue as ssh-agent we need to have in job configuration.

I am running 3 jobs now concurrently using same docker image:
1. My private build with JNLP launcher and ssh-agent, getting agent went offline issue.
2. Test Job with `sleep 100` command, JNLP launcher without ssh-agent, there also I am getting agent went offline issue.
3. My private build with SSH launcher, here till build 90, I have not faced any failures.

Will try to run each job separately and check result.

**Comment by KostyaSha** [comment]
> Test Job with sleep 100 command, JNLP launcher without ssh-agent, there also I am getting agent went offline issue.

And now try something like
```
#!/usr/bin/env bash

(
    while true
    do
        sleep 5 && echo "OUTPUT"
    done
)&

sleep 100
```

**Comment by deepraut89** [comment]
I run this job continuously for 30 builds alone and not faced any failures, then I enabled my private build job-1(as mentioned in previous comment) to run concurrently then faced the failure:

```
Building remotely on cloud-zeus-600bc59c93d6 (docker) in workspace /home/jenkins/workspace/yadp-testing
[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
[YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
[YAD-PLUGIN] DOCKER_HOST variable.
[yadp-testing] $ /usr/bin/env bash /tmp/hudson7143375663199441845.sh
OUTPUT
OUTPUT
OUTPUT
OUTPUT
OUTPUT
OUTPUT
OUTPUT
OUTPUT
OUTPUT
Agent went offline during the build
ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@6b8e4eb0[name=cloud-zeus-600bc59c93d6]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:629)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:137)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:310)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
	... 6 more

Build step 'Execute shell' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Finished: FAILURE
```

I will again disable my first job and try to run this alone today and observe the behaviour.

**Comment by KostyaSha** [comment]
Maybe check docker daemon logs?

**Comment by KostyaSha** [comment]
Hi, did you solve your issue? I found that NETTY implementation has some issues. Please try using JERSEY.
