### ISSUE TITLE
Docker jnlp launcher failed

### ISSUE THREAD

**Issue by qinyujia** [KostyaSha/yet-another-docker-plugin#120]
* YADP 0.1.0-rc29 & 0.1.0-rc30
* docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   47a8b59
 Built:        Tue Nov  8 01:22:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   47a8b59
 Built:        Tue Nov  8 01:22:25 2016
 OS/Arch:      linux/amd64                    
* Error message from slave container logs:
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
**"-cxe" is not a valid option** 
* System configuration:
![default](https://cloud.githubusercontent.com/assets/19236149/21503856/3912f326-cc95-11e6-937b-2fc1ce56d19c.png)
* Jenkins master log:
![default](https://cloud.githubusercontent.com/assets/19236149/21503916/b482a04c-cc95-11e6-8a91-90a583913bde.png)
Use the same Docker URL with Docker SSH  Launcher will work good. Please help to check, thank you.

**Comment by KostyaSha** [comment]
> Error message from slave container logs:
> Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
> "-cxe" is not a valid option

Something was changed in core. What is in your global security settings for agents?

**Comment by qinyujia** [comment]
here is my global security settings for agents
![default](https://cloud.githubusercontent.com/assets/19236149/21512092/dd046282-cce3-11e6-80bd-6936a3483524.png)

**Comment by KostyaSha** [comment]
what do you specify in `-url`?

**Comment by KostyaSha** [comment]
Sorry for delay, have no idea how missed notification.

**Comment by KostyaSha** [comment]
What core version do you use? It has some great regression in dev versions. Do you use lts?

**Comment by xiaoxuetu** [comment]
I  also meet this problem, my docker version is :
` {"Version":"17.04.0-ce","ApiVersion":"1.28","MinAPIVersion":"1.12","GitCommit":"4845c56","GoVersion":"go1.7.5","Os":"linux","Arch":"amd64","KernelVersion":"4.4.0-72-generic","BuildTime":"2017-04-03T18:07:42.793330938+00:00"}`

**Comment by jsdidierlaurent** [comment]
It's because you use jenkinsci/jnpl-slave. This container use script for starting slave.jar.
Use jenkinsci/slave with yet-another-docker-plugin and it will work.

**Comment by KostyaSha** [comment]
@jsdidierlaurent i switched from cmd to entrypoint and start script works fine starting from some version. 
Hope latest version resolved issue. If it still persist please reopen/comment.
