### ISSUE TITLE
JNLP Connector requires disabling strict verification

### ISSUE THREAD

**Issue by dddicillo** [KostyaSha/yet-another-docker-plugin#122]
I received the following error message when trying to connect to a slave container via JNLP using Jenkins 2.32.1:

```
Jan 10, 2017 12:28:43 PM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted connection #177 from gishiqaqgw07.dub.usoh.ibm.com/9.55.37.41:41187
Jan 10, 2017 12:28:48 PM WARNING jenkins.slaves.DefaultJnlpSlaveReceiver afterProperties
Rejecting connection to docker-swarm-1-7c1720169da6 from gishiqaqgw07.dub.usoh.ibm.com/9.55.37.41:41187 as a JNLP agent as the launcher class com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher does not extend JNLPLauncher or does not implement DelegatingComputerLauncher with a delegation chain leading to a JNLPLauncher. **Set system property jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true to allowconnections until the plugin has been fixed.**
Jan 10, 2017 12:28:48 PM INFO org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
[JNLP4-connect connection from gishiqaqgw07.dub.usoh.ibm.com/9.55.37.41:41187] Refusing headers from remote: docker-swarm-1-7c1720169da6 is not a JNLP agent
```

Setting that property corrects the error, but it seems like Jenkins should be detecting it on its own. Either way, I wanted to post this here in case anyone else is experiencing the same issue.

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/docs/USAGE.adoc#jenkins-configuration
The problem is that jenkins break java classes inheritance in backward incompatible way (lol for jenkins compatibilities). Hello to @stephenc. Maybe i will fix it in future, but not atm as it requires break existing inheritance while i'm working on new features.

**Comment by stephenc** [comment]
I think it would not break to have DockerLauncher extend either DelegatingComputerLauncher or the other one and just override the bits you need.

Or you could provide your own receiver and not change anything

**Comment by KostyaSha** [comment]
@stephenc yes, maybe i can introduce interface, but interface as ExtensionPoint isn't supported https://github.com/jenkinsci/jenkins/pull/2566 

I switched from DelegatingComputerLauncher as i don't need it. 
Why not simply introduce annotations? https://github.com/jenkinsci/jenkins/commit/1d16ce024c9049c1f05b45b48d5f8438e9303f4e#diff-10c460593867df19e7a7bc3a931b8a5bR68

**Comment by KostyaSha** [comment]
Btw with default methods interfaces will be fine instead of abstract class pattern.

**Comment by KostyaSha** [comment]
What is the security benefit it i can change extends to `DelegatingComputerLauncher` and it will bypass warning?

**Comment by stephenc** [comment]
Of it extends from delegating we follow the chain and allow if we find a JNLP launcher

**Comment by KostyaSha** [comment]
It seems that some `@Delegating` annotation may fit better.  But the main idea of not using delegating was because i need UI configs and prepare launcher before using it (because launcher may have internal variables). May i can change launcher producer to some Config<->real launcher duality...

**Comment by stephenc** [comment]
You should be able to achieve that with a jelly page that overrides the inheritance and just overriding the methods you need to override and not call super

**Comment by KostyaSha** [comment]
Or maybe even `grabLauncher` should be used.

**Comment by KostyaSha** [comment]
@stephenc what is the difference between `ComputerLauncherFilter` and `DelegatingComputerLauncher`?

**Comment by stephenc** [comment]
Why have one class when you can have two... seems too subtle for me to tell but I'm sure KK had a reason!

**Comment by KostyaSha** [comment]
@stephenc are both fine for 'security'? (maybe my classpathes conflicted with 1.609 vs 2.19 and i missed something)

**Comment by stephenc** [comment]
Both should be followed

**Comment by KostyaSha** [comment]
Yes, found. That's crazy :/

**Comment by KostyaSha** [comment]
@stephenc it is possible to do wait in Launcher if i right understand so waiting in Cloud.provision() sounds like additional delay in launch. So maybe Filter is what KK expected to do real connection wait?

**Comment by stephenc** [comment]
I'm currently brain-frazzled from scm-api work
