### ISSUE TITLE
Expose --shm-size for slaves

### ISSUE THREAD

**Issue by matthiasvegh** [KostyaSha/yet-another-docker-plugin#127]
I'd like my Jenkins slaves to have a ramdisk, and `/dev/shm` would suit my needs, but is limited to 64M.

Docker docs mention [`--shm-size`](https://docs.docker.com/engine/reference/run/#/runtime-constraints-on-resources), which would suffice. From what I can see, this is not available in the plugin.

**Comment by KostyaSha** [comment]
PR https://github.com/KostyaSha/yet-another-docker-plugin/pull/188
