### ISSUE TITLE
save docker slave container

### ISSUE THREAD

**Issue by sinycn** [KostyaSha/yet-another-docker-plugin#129]
hi
    i used yet another docker plugin with jenkins ,it works very well ,i want to know if it possible to save docker slave container, wish for your reply

**Comment by KostyaSha** [comment]
Hi, there is API for that but action to do save&push not implemented. Should be super easy to do. 
Do you have auth for push?

**Comment by sinycn** [comment]
i have auth for push,i will try to use api to solve it,ican you give a api link? thank you for your reply

**Comment by KostyaSha** [comment]
I started implementing here https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/DockerSlave.java#L167
It allows call Action attached to Computer. The idea is to commit and push container after it was stopped to exclude inmemory changes that slave.jar may do. 
But other-live commit&push variant may also work for docker. In this case you need create SimpleBuildStep/publisher/buildstep that will get computer, it's id, dockerclient and make actions with it.

**Comment by KostyaSha** [comment]
So what exactly variant do you need?

**Comment by sinycn** [comment]
thanks for your kindly help
