### ISSUE TITLE
[: true: unexpected operator in init.sh

### ISSUE THREAD

**Issue by GetchaDEAGLE** [KostyaSha/yet-another-docker-plugin#132]
It appears that [init.sh](https://github.com/KostyaSha/yet-another-docker-plugin/blob/d7e4d25477b3ca6ada565a3e70ddfcbf8f1140de/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh) has a problem on Line 51. It appears to be a problem with doing comparisons using "==" instead of "=". 

Please [see this](http://stackoverflow.com/questions/3411048/unexpected-operator-in-shell-programming) and [this](http://stackoverflow.com/questions/24464690/bash-scripting-unexpected-operator) for more details. Also, take a look at the output below. I'm using Ubuntu 16.04 as the Slave. I'm also using 0.1.0-rc31 of the plugin.

```bash
+ cat
+ chmod +x /tmp/init.sh
+ exec /tmp/init.sh
+ export CONFIG=/tmp/config.sh
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo No config, sleeping for 1 second
No config, sleeping for 1 second
+ sleep 1
+ [ ! -f /tmp/config.sh ]
+ echo Found config file
Found config file
+ . /tmp/config.sh
+ JENKINS_URL=https://obfuscated
+ JENKINS_USER=jenkins
+ JENKINS_HOME=/home/jenkins
+ COMPUTER_URL=computer/obfuscated/
+ COMPUTER_SECRET=obfuscated
+ JAVA_OPTS=-Xmx8192m -Djava.awt.headless=true -Duser.timezone=America/Chicago
+ SLAVE_OPTS=
+ NO_CERTIFICATE_CHECK=true
+ [ -z https://obfuscated ]
+ [ -z computer/obfuscated/ ]
+ [ -z /home/jenkins ]
+ id -u jenkins
1000
+ [ ! -d /home/jenkins ]
+ cd /home/jenkins
+ [ true == true ]
/tmp/init.sh: 51: [: true: unexpected operator
+ WGET_OPTIONS=
+ CURL_OPTIONS=
+ NO_SLAVE_CERT=
+ command -v wget
+ [ -x  ]
+ command -v curl
+ [ -x /usr/bin/curl ]
+ curl --remote-name https://obfuscated/jnlpJars/slave.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```

**Comment by GetchaDEAGLE** [comment]
I can confirm at this time that changing line 51 in **init.sh** from `if [ "$NO_CERTIFICATE_CHECK" == "true" ]` to `if [ $NO_CERTIFICATE_CHECK = true ]` resolved the problem. 

I used VIM to open `yet-another-docker-plugin.var` in the plugins folder and then edited `./com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh`. Afterward, I restarted Jenkins and tried again, this time with success.

The thing is, it's important that this script has the highest compatibility with the various shells that exist. From what I can decipher, the change I made should be compatible with just about any shell out there.

I find this rather interesting that nobody else has reported this problem. I'd certainly like to hear what people think of this issue.

**Comment by KostyaSha** [comment]
init.sh is correct, characters escaping is pain, i need check whether it possible to copy something into not running container. If not, then java escape should be fixed.

**Comment by KostyaSha** [comment]
Btw i got error with slave name starting from `-xx` because it interpret as argument.

**Comment by GetchaDEAGLE** [comment]
@KostyaSha, so this might be related to a character escaping issue then? Yes indeed, character escaping is never fun due to all the possibilities that exist, edge cases, etc. Is the character escaping issue somewhere in Java code?

**Comment by KostyaSha** [comment]
init.sh is correct, alphine has sh, but why it doesn't fail in it?

**Comment by KostyaSha** [comment]
Fixed without test for now...
