### ISSUE TITLE
Contribute script console script?

### ISSUE THREAD

**Issue by samrocketman** [KostyaSha/yet-another-docker-plugin#138]
I can write a script console script which configures this plugin via the Jenkins Script Console.  This helps to configure a large amount of clouds all in one go for this plugin and helps to stabilize master configurations for users of this plugin.

@KostyaSha would you be interested in me contributing a script console script?  It could go under `docs/scripts` as an idea.  Let me know.  I wouldn't mind taking ownership of the script and making updates to it.

**Comment by KostyaSha** [comment]
docs scripts are fine

**Comment by samrocketman** [comment]
Great!  I'll work on it this weekend and contribute it back.

**Comment by fboudra** [comment]
@samrocketman great, it's something I wanted to do but didn't progress due to lack of time. fwiw, I was looking for starting from what the riotgames guys have done: https://github.com/maxfields2000/dockerjenkins_tutorial/tree/master/jenkinsscripts

**Comment by samrocketman** [comment]
@fboudra thanks for the pointer at Riot Games scripts.  I'll look them over for inspiration.  I already have a good idea for how the script can be scalable for others.

**Comment by samrocketman** [comment]
I'll contribute a script for `0.1.0-rc31`.  I'll update the script when #136 is fixed.

**Comment by samrocketman** [comment]
@fboudra I contributed the script in #139.  It's much more robust than examples listed in https://github.com/maxfields2000/dockerjenkins_tutorial/tree/master/jenkinsscripts.

It's using JSONArray and JSONObject to configure an unlimited number of clouds with an unlimited number of templates.
