### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by erik-am** [KostyaSha/yet-another-docker-plugin#151]
@KostyaSha Thanks for your efforts, so that TLS is supported!

I was wondering if you could also incorporate support for Windows containers. Changes for the original Docker plugin are still in this PR: https://github.com/jenkinsci/docker-plugin/pull/465

**Comment by KostyaSha** [comment]
Should be possible, but i have no windows for testing :D

**Comment by erik-am** [comment]
@KostyaSha Maybe if you can replicate the changes from the referenced PR, I would be willing to test it on Windows. :wink:

**Comment by KostyaSha** [comment]
@erik-am can i run some windows in virtualbox?

**Comment by KostyaSha** [comment]
@gamma do you want implement it? I installed windows 10 enterprise on virtualbox, but docker is crashing. I don't know where i can get docker containers.

**Comment by gamma** [comment]
This is the set of Docker images we're using: https://github.com/i-net-software/docker-boxes/tree/master/build-slaves/windows

I can try to incorporate the JNLP changes though I'm more interested in an SSH variant. I can have a look - but no promises.

**Comment by KostyaSha** [comment]
@gamma ssh is evil!

**Comment by KostyaSha** [comment]
> This is the set of Docker images we're using: https://github.com/i-net-software/docker-boxes/tree/master/build-slaves/windows

I have osx and i can't get anything locally. It seems that virtualbox can't emulate right env?

**Comment by gamma** [comment]
I'm using OSX as well.

Not sure, I've not tested the windows docker variant, only docker EE on windows 2016 with a bare metal server. AFAIK Win 10 should support the windows container service but I do not know how it works.

**Comment by pronovic** [comment]
I have also submitted pull request #163 related to this functionality.   I did not run across #157 until after @louisn and I had finished building and testing our version, so I decided to submit it anyway -- in case it's useful.  I'm not sure what state #157 is in, since it doesn't seem to have moved recently.   @louisn and I tested with Docker 17.03.1-ce-win12 (12058) on Windows 10 Enterprise.

**Comment by KostyaSha** [comment]
Seems @pronovic PR contains more changes, i'm reviewing it. @gamma you are welcome to join review.
