### ISSUE TITLE
Support docker run --init option

### ISSUE THREAD

**Issue by samrocketman** [KostyaSha/yet-another-docker-plugin#165]
Newer versions of docker support [`docker run --init`](https://docs.docker.com/engine/reference/commandline/run/).  `docker run --init` uses a proper init for cleaning up processes in long running containers.

If you support this option, you can essentially remove the following comments.

- https://github.com/KostyaSha/yet-another-docker-plugin/blob/98ecf0a17ccbab6ba6913bdb82f97f6de54fb0bb/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerSingleJNLPLauncher.java#L246
- https://github.com/KostyaSha/yet-another-docker-plugin/blob/6761d28443b922a72b4e7df99b58444484c48135/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java#L176

**Comment by KostyaSha** [comment]
AFAIR it bit different. https://stackoverflow.com/questions/43122080/how-to-use-init-parameter-in-docker-run
We have no forks here, only execs. First command that waits for config, then it prepares everything and exec slave.
Under PID 1 replacement i mean get rid of intermediate processes and make slave jar PID 1 in the end.

**Comment by samrocketman** [comment]
A build, by nature, will fork from the agent.  Long running builds exist.  In any case this is easily resolved by setting a container entrypoint.  It would be nice not to require baking an init but it's a minor layer in Docker.
