### ISSUE TITLE
[YAD-PLUGIN] Injecting <XYZ> variable.

### ISSUE THREAD

**Issue by MichaelSp** [KostyaSha/yet-another-docker-plugin#171]
are all these log messages really necessary?
For me they just make it harder to read my console log. Can we remove them?

**Comment by KostyaSha** [comment]
Yes, sure. Also need end #105

**Comment by warandpeace** [comment]
+1 to removing these log messages or making them optional. It's a big source of frustration with this plugin.

**Comment by KostyaSha** [comment]
They will be printed only when they are injected, already existing configs will have old behaviour. If you don't need vars you can remove node property in template configuration.
