### ISSUE TITLE
Building the plugin

### ISSUE THREAD

**Issue by nbars** [KostyaSha/yet-another-docker-plugin#175]
Hey,
I would like to contribute to you're project, but as there is no documentation how to setup
the project (I am totally new to maven) I am stuck in compiling the software.

I have forked the master branch and when I hit build on IDEA I get the following error:
```
/home/nils/git/yet-another-docker-plugin/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/commons/DockerCreateContainer.java
Warning:(4, 52) java: com.cloudbees.jenkins.plugins.sshcredentials.SSHUserListBoxModel in com.cloudbees.jenkins.plugins.sshcredentials has been deprecated
Error:(7, 78) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.command does not exist
Error:(8, 76) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model does not exist
Error:(9, 76) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model does not exist
Error:(10, 76) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model does not exist
Error:(11, 76) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model does not exist
Error:(12, 76) java: package com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model does not exist
...
```

Thanks in advance!

**Comment by samrocketman** [comment]
Hi @nbars, this project uses Maven wrapper so most of what you need comes included "out of the box".  You just need to provide Java 8.

Here's an example of how I build it (assuming your working directory is the root of this repository):
```
export JAVA_HOME="$HOME/usr/java/oraclejdk8"
export PATH="$JAVA_HOME/bin:$PATH"
./mvnw clean package
```

The build result will be in: `yet-another-docker-plugin/target/yet-another-docker-plugin.hpi`.  The HPI file is what you load into Jenkins.

**Comment by KostyaSha** [comment]
> The HPI file is what you load into Jenkins.

With dependencies.

**Comment by nbars** [comment]
Thanks, building works the way you described. But is there any way to get rid of the error messages in IDEA (see first post)? It would be great if I cloud follow references e.g. to see whats called methods actually do...

**Comment by KostyaSha** [comment]
IDEA doesn't understand shaded artifacts.  Call `install` for root module and then `In IDEA manually attach docker-java-shaded…​.jar to plugin and its modules (no idea why IDEA doesn’t see deps)`

**Comment by nbars** [comment]
By calling install you mean ``./mvnw clean install``? An could you elaborate on the steps I have to do to *attach* the .jar file? Also there is not even a ``docker-java-shaded...jar`` file anywhere. Thanks

**Comment by KostyaSha** [comment]
> Also there is not even a docker-java-shaded...jar file anywhere

it under corresponding maven module https://github.com/KostyaSha/yet-another-docker-plugin/tree/master/yet-another-docker-java

**Comment by KostyaSha** [comment]
I'm thinking on moving shaded module to external repository.... Should simplify usage.
