### ISSUE TITLE
Support for setting shared memory size (--shm-size) for docker slaves

### ISSUE THREAD

**Issue by fboudra** [KostyaSha/yet-another-docker-plugin#181]
In our environment, we need to use --shm-size for some use cases. The option isn't exposed currently.
There's an existing PR for docker plugin: https://github.com/jenkinsci/docker-plugin/pull/497

Is it the way forward or what do you suggest to pass this option?

For reference: https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources

**Comment by KostyaSha** [comment]
if it exists in docker-java should be pretty simple

**Comment by KostyaSha** [comment]
duplicates #127

**Comment by fboudra** [comment]
PR #188
