### ISSUE TITLE
Create Container Settings UI show exception

### ISSUE THREAD

**Issue by seanly** [KostyaSha/yet-another-docker-plugin#194]
![image](https://user-images.githubusercontent.com/232069/30623553-d9254fea-9dea-11e7-80c4-0a4d33a16928.png)
default height=0
version: rc40

blank display
![image](https://user-images.githubusercontent.com/232069/30623580-fd112442-9dea-11e7-8fcb-2f5de32259e1.png)
， but existing content
![image](https://user-images.githubusercontent.com/232069/30623616-480ab2e2-9deb-11e7-89fb-38c911b2d431.png)

**Comment by KostyaSha** [comment]
For what configuration are you trying to fill this setting?

**Comment by samrocketman** [comment]
Create container docker command is for executables and not SSH public keys.

Additionally, you appear to have fancy quotes pasted.  I wouldn't be surprised if you had fancy quotes in other parts of your confit as well.  Double check you're not using invalid characters like fancy quotes.

I wonder if YADP could validate for these kinds of things?  Maybe not worth it.

**Comment by KostyaSha** [comment]
launchers will override this command, so this setting makes no sense for DockerCloud
