### ISSUE TITLE
successful pull on legacy swarm throws Exception

### ISSUE THREAD

**Issue by scddev** [KostyaSha/yet-another-docker-plugin#196]
Using version 0.1.0-rc40:

When specifying the image name with "some.repo:6000/library/someimage:latest" the "Pull once but always update latest" strategy fails. If you do not specify the tag "latest" it is working fine. Even though the response from swarm indicates the ": downloaded" which is checked in PullResponseItem.java.

```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Pulling some.repo:6000/library/someimage:latest... : downloaded
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at com.github.kostyasha.yad.commons.DockerPullImage.exec(DockerPullImage.java:145)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:227)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:136)
	at com.github.kostyasha.yad.DockerCloud.dt_access$761(DockerCloud.java)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by scddev** [comment]
It seems like docker-java 3.0.13 is not in line with the sources from github:

https://repo.maven.apache.org/maven2/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13-sources.jar

PullResponseItem.java looks outdated, not containing the check for swarm if compared to: https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/PullResponseItem.java

**Comment by KostyaSha** [comment]
> It seems like docker-java 3.0.13 is not in line with the sources from github:

everything is right, docker-java master != 3.0.x
As soon as i end docker-java master updates we will get update in yad.

**Comment by scddev** [comment]
Thanks, sorry, my bad, I did not check 3.0.x branch on docker-java.

**Comment by KostyaSha** [comment]
I can make you experimental hpi if you want :)

**Comment by scddev** [comment]
Either that, or if you have a branch I can checkout, I can build it myself.

**Comment by KostyaSha** [comment]
You can try 'mvn install' locally for docker-java master branch and switch yad module to docker-java snapshot and `./mvnw install -DskipTests`

**Comment by scddev** [comment]
Ahh, I assumed you had also some changes on the yad module. Yep, switching to 3.1.0-SNAPSHOT works. Now also pulling latest tag with legacy swarm works.

```
Sep 27, 2017 12:58:27 PM INFO com.github.kostyasha.yad.DockerCloud provision
Asked to provision load: '1', for: 'xxx' label
Sep 27, 2017 12:58:27 PM INFO com.github.kostyasha.yad.DockerCloud provision
Will provision 'xxx:6000/library/xxx:latest', for label: 'xxx', in cloud: 'yad'
Sep 27, 2017 12:58:30 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'xxx:6000/library/xxx:latest' number '0' on 'yad'; Total containers: '0'
Sep 27, 2017 12:58:30 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning xxx:6000/library/xxx:latest from yad with 1 executors. Remaining excess workload: 0
Sep 27, 2017 12:58:30 PM INFO com.github.kostyasha.yad.commons.DockerPullImage exec
Pulling image 'xxx:6000/library/xxx:latest' again. This may take awhile...
Sep 27, 2017 12:58:31 PM INFO com.github.kostyasha.yad.commons.DockerPullImage exec
Finished pulling image 'xxx:6000/library/xxx:latest', took 927 ms
Sep 27, 2017 12:58:38 PM INFO com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
```

**Comment by KostyaSha** [comment]
Cool, afair master snapshot builds from docker-java should be uploaded automatically... but i not sure. Will check later.

**Comment by KostyaSha** [comment]
Hi, adding workaround in #207

**Comment by KostyaSha** [comment]
please try new version.

**Comment by scddev** [comment]
Thanks, works for now.
