### ISSUE TITLE
thoughts on overwriting ENTRYPOINT or skip running init.sh?

### ISSUE THREAD

**Issue by domofactor** [KostyaSha/yet-another-docker-plugin#200]
I recently ran into an issue with the JNLP launcher around the entrypoint's init.sh script.

I need be able to kick both init.sh and dockerd at the same time under the supervisord command.

However, because the ENTRYPOINT is being overwritten, even if I specify a custom CMD from the options, due to [this](https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh#L112) line in init.sh, the slave.jar runs and CMD never actually executes.

Do you have any recommendations/thoughts for the following?

1. making ENTRYPOINT customizable in the plugin options
1. having some way to skip executing that last line inside of init.sh, or init.sh itself during the ENTRYPOINT, so we can run something else later on via CMD.(supervisord in this case)

thanks! 😄

**Comment by KostyaSha** [comment]
keeping entrypoint may raise a lot of issues. Now container is just a build container, when slave scripts exist - container stops. If i keep entrypoint, then container may shutdown in any time that will interrupt build with unknown reason. init.sh and entrypoint+cmd override allows to use any image with java for launching slave. 
Imho better think how to run side containers if you need run some tool.

**Comment by wenlock** [comment]
Would adding a config option for the init script to eval "preinit.sh" & as a part of the init.sh or even config.sh script?

Then any running things needed for the build are there ahead of time as part of the init process.

**Comment by KostyaSha** [comment]
Any additional long life process (not just some shell commands) will require init system, either signal wouldn't be delivered to slave.jar... It may be possible to save entrypoint and call it, but it shouldn't produce new processes.

**Comment by domofactor** [comment]
thanks for the feedback @KostyaSha! 👍 

We were able to get things working by using the SSH launcher instead of JNLP and kicking `supervisord` as the docker CMD which in turn runs `dockerd` and `sshd`.

**Comment by KostyaSha** [comment]
well.. it's bad that you can do something with ssh, but can't with jnlp. Though sshd itself is daemon that wouldn't pass signals to childs and that's also problem. I don't suggest to use ssh, it has very crazy synchronization bugs...
Could you describe your use case? What exactly do you want to run and it impossible to run from job or as side container?
