### ISSUE TITLE
Delete Older Docker Images

### ISSUE THREAD

**Issue by Pranav1210** [KostyaSha/yet-another-docker-plugin#210]
I keep updating my docker images and upload them on docker image. The plugin pulls the image every time but does not delete the old image. The hard disk is getting filled every 2 3 weeks. Can plugin support deleting old images when it pulls the new image.

**Comment by KostyaSha** [comment]
I think the right solution will be not to do it from jenkins, https://github.com/spotify/docker-gc in cron may be better solution.
