### ISSUE TITLE
Support for build arguments

### ISSUE THREAD

**Issue by crisp2u** [KostyaSha/yet-another-docker-plugin#212]
Hi Guys, 

Is there a support for build arguments ? So far I could not find anything. 

Thanks

**Comment by samrocketman** [comment]
What arguments are you looking to configure?  As far as I know this plugin only executes `docker run` and not docker build.

**Comment by crisp2u** [comment]
I might be confused by other plugins but I'm seeing a build/publish docker container buildstep and for that I was looking for args support.

**Comment by KostyaSha** [comment]
I have it but it hidden from users, could you show the screenshot?

**Comment by crisp2u** [comment]
I ment this [Build/Publish Docker Image](https://www.dropbox.com/s/etcu2yp0ws12pkm/Screenshot%202017-11-10%2023.28.56.png?dl=0) I was thinking of using it to build and publish container instead of shell script with docker commands

**Comment by KostyaSha** [comment]
Press help button and it you will see from what plugin is this help. I think this garbage is from docker-plugin. I will expose build step later for users.

**Comment by crisp2u** [comment]
You're right, it's coming from the docker-plugin. When you mean "garbage" you want to say that it's bad implemented or it does not make sense to have a build step like that? Then why do you want to expose it still, I'm a bit confused.

**Comment by KostyaSha** [comment]
For me docker-plugin is garbage, especially now when the worst quality developer "fixing" it ))

**Comment by crisp2u** [comment]
Yes, I'm having issues myself with that plugin, but I think we should delete this issue, there is enough flame around here ...
