### ISSUE TITLE
Docker slave versioning

### ISSUE THREAD

**Issue by DePuysseleyrMats** [KostyaSha/yet-another-docker-plugin#215]
Hi
I would like to know if there is a way to automatically add a docker template to the jenkins configuration. I want to make use of docker versioning so that I can create another docker image with a jenkins job of another version of the build tool I use. That way I can easily assign jobs with the docker container that has the correct version. I am able to create these containers through a jenkins job but I haven't found a way to add the corresponding configuration to the cloud configuration page. Is there a way to automatically add this config? Or do I need to manually add them after each version?

Thanks

**Comment by KostyaSha** [comment]
ideally it should be offloaded to job configuration. I have one WIP branch with exposing configuration into job property. In insecure way you can manipulate with cloud configuration from system groovy script execution.

**Comment by DePuysseleyrMats** [comment]
and what function should I use if I want to add a docker slave to the cloud configuration?

**Comment by DePuysseleyrMats** [comment]
I've managed to add templates to an existing cloud by using this script.
`import com.github.kostyasha.yad.DockerCloud
import com.github.kostyasha.yad.DockerSlaveTemplate
import com.github.kostyasha.yad.DockerContainerLifecycle
import com.github.kostyasha.yad.commons.DockerCreateContainer
import com.github.kostyasha.yad.commons.DockerStopContainer
import com.github.kostyasha.yad.commons.DockerRemoveContainer
import com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy
import hudson.slaves.*
import hudson.plugins.sshslaves.SSHConnector
import com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher
  
DockerRemoveContainer dockerremove = new DockerRemoveContainer()
dockerremove.setRemoveVolumes(false)

DockerStopContainer dockerstop = new DockerStopContainer()
dockerstop.setTimeout(10)

DockerCreateContainer dockercreate = new DockerCreateContainer()
List<String> volumes = ["/var/lib/"]
dockercreate.setVolumes(volumes)

DockerContainerLifecycle docklife = new DockerContainerLifecycle()
docklife.setImage("test")
docklife.setCreateContainer(dockercreate)
docklife.setStopContainer(dockerstop)
docklife.setRemoveContainer(dockerremove)

RetentionStrategy retstrat = new DockerOnceRetentionStrategy(10)

SSHConnector sshConnector = new SSHConnector(22, "","","","","",120,10,10)
ComputerLauncher complauncher = new DockerComputerSSHLauncher(sshConnector)

DockerSlaveTemplate dockslave = new DockerSlaveTemplate()
dockslave.setDockerContainerLifecycle(docklife)
dockslave.setRemoteFs("/home/jenkins")
dockslave.setLabelString("test")
dockslave.setRetentionStrategy(retstrat)
dockslave.setMode(Node.Mode."EXCLUSIVE")
dockslave.setLauncher(complauncher)


DockerCloud dock = com.github.kostyasha.yad.DockerCloud.getCloudByName("local dockerhost")
dock.addTemplate(dockslave)`

**Comment by KostyaSha** [comment]
Yes, that what i mean :)

**Comment by DePuysseleyrMats** [comment]
How can I add a docker registry host through my system groovy script? What object do I need for this to work? I can't seem to find it in the API.

**Comment by KostyaSha** [comment]
Not sure that i correctly understand. Registry is needed only fro pulling image and it uses Credentials. 
So for successfull pull. You need `getContainerLifecycle().getPullImage().setRegistriesCreds(ArrayList.asList(new DockerRegistryCredential("registryaddress", "credentialsId")))`
where credentials id is docker registry credential added to credentials

**Comment by DePuysseleyrMats** [comment]
Ah I think that's what I was looking for, it seems like the DockerRegistryCredential class is not present on the javadoc pages. Thanks! :)
![4b92762dd77b0410fc9998e822ce0bfe](https://user-images.githubusercontent.com/11004904/32611773-c7397434-c566-11e7-937c-484e4a6a835d.png)

**Comment by KostyaSha** [comment]
@DePuysseleyrMats it comes from docker-commons

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/DockerContainerLifecycle.java#L32-L40

https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/commons/DockerPullImage.java#L60

**Comment by KostyaSha** [comment]
and pulling logic is here https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/commons/DockerPullImage.java#L112
DockerRegistryAuthCredentials < is the only supported type atm

**Comment by samrocketman** [comment]
See also https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/docs/script-console-scripts/configure-yadocker-cloud.groovy for configuring settings.

Here's how I configure credentials for other types.  It wouldn't be hard to expand it to configure credentials for docker registries or refer to it.

**Comment by KostyaSha** [comment]
@samrocketman he needs only add cloud, so your merge strategy is not really required + xml save() should happen during cloud.add() call. So his variant should work exactly.

**Comment by DePuysseleyrMats** [comment]
Yup I only needed to add a slavetemplate to an already existing cloud. I did however took a lot of inspiration from the configure-yadocker-cloud.groovy script :) but still thanks for the support!

**Comment by KostyaSha** [comment]
If you need only add, then you need getCloud(), change internals and call save() on jenkins instance.
