### ISSUE TITLE
Running container slave as non-root user

### ISSUE THREAD

**Issue by vsantos** [KostyaSha/yet-another-docker-plugin#217]
Hello folks,

Can you help me to understand 'user' expected behavior for container-slaves? 

In tag `0.1.0-rc45` at commit db0026e was introduced a feature that will run a container as `root` if the docker-template (docker image) have changed the default user. It supposed to be hardcoded user `root` for this kind of situation? Unlike Hostname option (at 'Create Container Settings') the User option cannot be used, Im still running the slave as `root`.

In our company, we will not run any containers as root due to a security Docker best practice. Is there any workaround or maybe Im just missing a point?

I tried to find similar open issues, without success.

Thank you in advance

<img width="1280" alt="screen shot 2017-11-22 at 12 53 07" src="https://user-images.githubusercontent.com/16156133/33133501-2523762c-cf84-11e7-9204-365036f15fad.png">

```
[login@docker-cloud-01 ~]$ sudo docker exec -it aacd702719f0 hostname
temp-hostname
[login@docker-cloud-01 ~]$ sudo docker exec -it aacd702719f0 id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by KostyaSha** [comment]
@victorssouza root is used to run init.sh that prepares env for slave execution and then downgrades permission downto to configured user in launcher. 
To have ability to launch slave in any image entrypoint should be reseted and root user used.
Though probably if you have init user and target user equal root may not be needed. 

Probably "root" enforcement should be set in "create container settings" and be configurable for user. 
Really want rethink the configuration of possible launching. On one hand we can add multiple launchers, on other their differences may exist as configuration under one launcher

**Comment by enconti** [comment]
@KostyaSha, 
@victorssouza and I tried to set user in "create container settings" and in Launcher "Linux User" configuration, but container always starts with root user, and the user that we set was ignored.

We expected that "Linux User" was used instead of root since we set it, as explained on Help.

<img width="771" alt="screen shot 2017-11-22 at 6 17 07 pm" src="https://user-images.githubusercontent.com/833047/33148172-e3156fbe-cfb1-11e7-81f8-0b43dd5bc40e.png">

We are experiencing this issue after 0.1.0-rc45 update, before this update was working as expected.

**Comment by KostyaSha** [comment]
@enconti this is configuraiton from launcher - this is under what user slave will run, container with initial script will run under root atm (hardcoded).  Could you show what is in slave log? Run build with sleep 1000 and navigate to slave-> log.

**Comment by victorssouza** [comment]
@KostyaSha @enconti Sure! No problem

Container starts with no problem with a root user, our real issue is that root is not being switch to our desired user. We are using JNLP Launcher.

Im attaching a sanitized version of the logs about the running container.

[docker-slave.log](https://github.com/KostyaSha/yet-another-docker-plugin/files/1497474/docker-slave.log)

**Comment by samrocketman** [comment]
When building your docker images.  If you set `USER jenkins`, then YADP will not try to switch users if you set `user = jenkins` in the config.

[Notice in `init.sh` it will not `su` if the current user is already `$JENKINS_USER`](https://github.com/KostyaSha/yet-another-docker-plugin/blob/0.1.0-rc46/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh#L108-L114).  No need to run root to begin with.

**Comment by KostyaSha** [comment]
@samrocketman i found the case when USER XX was defined in image and init.sh failed, so added enforcement. @victorssouza remind me that this could be done without code enfocrement by using already existing create container user value. I will remove enforcement and set default in create.

**Comment by victorssouza** [comment]
@KostyaSha Thanks for your support, I will be glad to help in any way I can.

**Comment by samrocketman** [comment]
@KostyaSha I have an example container which is small and able to reproduce this error.  Please see https://github.com/samrocketman/docker-jenkins-jervis/blob/master/alpine/Dockerfile

When running as the `jenkins` user it executes an invalid command:

```
su - jenkins -c java -jar slave.jar -noReconnect -workDir /home/jenkins -jnlpUrl http://172.17.0.1:8080/computer/docker-local-41ed1bb686e4//slave-agent.jnlp -secret REDACTED
```

It would be nice if it executed:

```
java -jar slave.jar -noReconnect -workDir /home/jenkins -jnlpUrl http://172.17.0.1:8080/computer/docker-local-41ed1bb686e4//slave-agent.jnlp -secret REDACTED
```

**Comment by samrocketman** [comment]
Strangely, the container is started as `root` every time.  I'm not sure why it forces root.  I'm using alpine linux and even something as simple as the following fails.

```
su - jenkins -c '/bin/bash -c "echo hello"'
```

If it was adhering to my `USER` setting and running the straight Java command, then it would execute without issue.

**Comment by samrocketman** [comment]
I may have found my problem.  There's two places for setting the `user`:
* Container settings.
* JNLP launcher settings.

I have only set the JNLP launcher.

**Comment by samrocketman** [comment]
Likely the problem: https://github.com/KostyaSha/yet-another-docker-plugin/blob/db0026ea46b1ca24a03c4212d09acefff0b1f2e4/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/steps/DockerShellStep.java#L142-L146

**Comment by KostyaSha** [comment]
> Likely the problem:

That's example from dockerShellStep. That's the way to provide flexibility. If you use stock executor (script that handles different stuff before user shell script) it enforces perms for stock executor.

Launchers bit different.

**Comment by samrocketman** [comment]
Yeah I realize that now.  My pull request fixes the existing bug preventing containers from running as non-root.

**Comment by samrocketman** [comment]
@vsantos please verify.
