### ISSUE TITLE
Is there a method to reduce/remove the [YAD-PLUGIN] logging information in the build log?

### ISSUE THREAD

**Issue by jlouisfoster** [KostyaSha/yet-another-docker-plugin#232]
Hi,

I would like to know if there is a way to reduce the level of logging output in the build log itself.
I would like to remove the ..

[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.

For example and only keep the build information.

Thanks.

**Comment by KostyaSha** [comment]
Yes, it possible... DockerEnvironmentContributor needs change, but this information was used in test, so test need to be adjusted also...

**Comment by KostyaSha** [comment]
There were change before and variables are printed only when they are enabled for Node variables insertion.
