### ISSUE TITLE
Allow Users to specify the VolumeDriver to use

### ISSUE THREAD

**Issue by cfraenkel** [KostyaSha/yet-another-docker-plugin#241]
I'd like to specify the VolumeDriver that should be used when volumes are created on a jenkins slave container. docker-java already supports this attribute (it belongs to HostConfig).

The usecase is that I would like to use https://github.com/suryagaddipati/docker-cache-volume-plugin to reuse build caches between containers.

Could you please add support for this setting to the yet-another-docker-plugin?

**Comment by KostyaSha** [comment]
will check

**Comment by cfraenkel** [comment]
I don't require this feature anymore
