### ISSUE TITLE
Question: downstream jobs

### ISSUE THREAD

**Issue by prom3theu5** [KostyaSha/yet-another-docker-plugin#253]
Currently in the process of migrating from two static Jenkins masters to a single master with containers 

I’ve converted half of our jobs to multibranch pipelines which run shared tools (groovy) for jobs 

However we still have 80 jobs which are freestyle projects that trigger a shared downstream project which in turn triggers a third for unit tests

Is there a way to have those downstream projects run in the same container as the initial upstream container?

Atm they are three containers when it runs with a shared (bind volume) as a workspace

**Comment by KostyaSha** [comment]
There are configurable retention policies, but i have no idea how to lock jobs to newly created container.
