### ISSUE TITLE
IllegalAccessError after upgrading to latest SSH Slaves 1.31.0 and matching Jenkins 2.190.1

### ISSUE THREAD

**Issue by eliasbalasis** [KostyaSha/yet-another-docker-plugin#275]
After upgrading Jenkins to 2.190.1 and SSH Slaves to 1.31.0 we are getti g the following error every time "Yet Another Docker" starts a new build job.

`
java.lang.IllegalAccessError: tried to access field hudson.plugins.sshslaves.SSHConnector.jvmOptions from class com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getSSHLauncher(DockerComputerSSHLauncher.java:126)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getPreparedLauncher(DockerComputerSSHLauncher.java:63)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:265)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

We tried to re-create "Docker Template" and even work with a new "Yet Another Docker Cloud".
Nothing worked, the above error is always produced.

We believe this is a "Yet Another Docker" compatibility issue with latest version of Jenkins or the SSH Slaves plugin.

This is very critical, it is breaking our build process,.

Please assist as soon as possible.

**Comment by eliasbalasis** [comment]
FYI we use latest "Yet Another Docker" 0.1.3

**Comment by eliasbalasis** [comment]
Deeper investigation reveals that `com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getSSHLauncher`
is trying to access `hudson.plugins.sshslaves.SSHConnector.jvmOptions` directly (among other fields), but the fields are `private`
These directly accessed fields used to be `public` up to [SSH Slaves 1.29.4](https://github.com/jenkinsci/ssh-slaves-plugin/blob/ssh-slaves-1.29.4/src/main/java/hudson/plugins/sshslaves/SSHConnector.java)

I believe this explains the problem.

This is very critical and is breaking our build process,.
Please assist as soon as possible.

**Comment by KostyaSha** [comment]
temporary revert ssh-slaves plugin that broke binary compability

**Comment by eliasbalasis** [comment]
Indeed, SSH Slaves plugin has broken binary compatibility.

However, Jenkins cannot downgrade to SSH Slaves 1.29.4 which puts us in a dead end position.

Can this be fixed on Yet Another Docker plugin side?

**Comment by KostyaSha** [comment]
> Jenkins cannot downgrade to SSH Slaves 1.29.4

why? core doesn't depend on ssh slaves plugin afair.



> Can this be fixed on Yet Another Docker plugin side?

II prepared PR but had no time, will try to look

**Comment by eliasbalasis** [comment]
Thanks,

This is unfortunately a one way street for us and perhaps other users as well.

We have upgraded to Jenkins 2.190.1 which doesn't let us downgrade to SSH Slaves earlier than 1.30.2, for whatever reason.

We can either hope that SSH Slaves plugin team will revert the broken binary compatibility or hope that you can fix this on Yet Another Docker plugin side.

I personally find less likely SSH Slaves restoring the compatibility.

Unfortunately, if you try to fix this on Yet Another Docker plugin side, you will break compatibility with earlier versions of SSH Slaves.

Sadly, since Yet Another Docker plugin is a consumer of SSH Slaves, I assume it is better to follow the direction SSH Slaves is following rather than trying to force SSH Slaves follow an obsolete approach.

Users of subsequent Yet Another Docker plugin releases will have to use SSH Slaves 1.30.0 or later.

Do you agree?

**Comment by KostyaSha** [comment]
It seems that xml can pick changed class, updated #262 . Probably should work. Somehow even constructor arguments conflicting. `Jenkins 10 years of binary compatibility` is myth.
Would you like to test .hpi from PR?

**Comment by eliasbalasis** [comment]
The PR seems to be using the getters and setters now for related SSH Slave classes.

How can I get the `.hpi` file from the PR?

**Comment by KostyaSha** [comment]
You are not taking into account class. I will gave a link once it compile

**Comment by KostyaSha** [comment]
https://jitpack.io/com/github/KostyaSha/yet-another-docker-plugin/yet-another-docker-plugin/sshConnectorBreakage-0.1.3-g298b5b3-10/yet-another-docker-plugin-sshConnectorBreakage-0.1.3-g298b5b3-10.hpi

**Comment by eliasbalasis** [comment]
Thanks Kanstantin,

this seems to be working, I can now run build jobs without `java.lang.IllegalAccessError`

Are you planning to officially release this?
