### ISSUE TITLE
NullPointerException, stuck provisioning slave

### ISSUE THREAD

**Issue by ericliboon** [KostyaSha/yet-another-docker-plugin#282]
Getting NPE and none from the jobs assigned from the label was executed, stuck in provisioning slave. Configured to use Docker JNLP launcher

Test connection:
Test Connectioncom.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Version@284948ce[  apiVersion=1.25  arch=amd64  gitCommit=b830072b  goVersion=go1.8.6  kernelVersion=-  operatingSystem=linux  version=1.5.0  buildTime=Mon Jan 14 03:05:43 2019  experimental=true  minAPIVersion=1.19  platform=<null>  components=<null>]
--

```


Asked to provision load: '1', for: 'DBSITSSVCH' label
Mar 04, 2020 5:12:01 AM INFO com.github.kostyasha.yad.DockerCloud provision
Will provision 'x18gvichub01a..cloudnow.com/its-dcif-01/jenkins-slave:3.0', for label: 'DBSITSSVCH', in cloud: 'DBSSLAVE'
Mar 04, 2020 5:12:01 AM WARNING com.github.kostyasha.yad.DockerCloud provision
Bad template 'x18gvichub01a.cloudnow.com/its-dcif-01/jenkins-slave:3.0' in cloud 'DBSSLAVE': 'null'. Trying next template...
java.lang.NullPointerException
	at com.github.kostyasha.yad.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:321)
	at com.github.kostyasha.yad.DockerCloud.addProvisionedSlave(DockerCloud.java:343)
	at com.github.kostyasha.yad.DockerCloud.provision(DockerCloud.java:114)
	at com.github.kostyasha.yad.DockerProvisioningStrategy.apply(DockerProvisioningStrategy.java:91)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:62)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
Could you post part of global config.xml related to this templated/cloud?

**Comment by KostyaSha** [comment]
And this:
```
def client = Jenkins.instance.getCloud("DBSSLAVE").getClient()
containers = client.listContainersCmd().exec().each(){ container -> 
  print(container.getId() + " -> ")
	print(container.getLabels())
}

println()
```

**Comment by ericliboon** [comment]
Hi @KostyaSha 

please refer to below for the config.xml:

 <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.5">
      <name>DBSSLAVE</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>59178337-b430-4342-9b4b-097dcb2edc35</id>
          <labelString>DBSITSSVCH</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher">
            <launchTimeout>200</launchTimeout>
            <user></user>
            <jvmOpts></jvmOpts>
            <slaveOpts></slaveOpts>
            <jenkinsUrl></jenkinsUrl>
            <noCertificateCheck>true</noCertificateCheck>
            <reconnect>false</reconnect>
          </launcher>
          <remoteFs>/home/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>1</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">1</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>x18gvichub01a.prd.cloudnow.dbs.com/its-dcif-01/jenkins-slave:3.0</image>
            <pullImage>
              <pullStrategy>PULL_LATEST</pullStrategy>
              <credentialsId>1231b574-b883-4d6f-a05a-4b7f5771be42</credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>false</bindAllPorts>
              <memoryLimit>0</memoryLimit>
              <privileged>false</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
              <dockerLabels class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dockerLabels>
              <shmSize>0</shmSize>
              <restartPolicy>
                <policyName>NO</policyName>
                <maximumRetryCount>0</maximumRetryCount>
              </restartPolicy>
              <workdir></workdir>
              <user></user>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>true</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <configVersion>1</configVersion>
          <maxCapacity>10</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>50</containerCap>
      <connector>
        <serverUrl>tcp://x18gdcifvch02b.prd.cloudnow.dbs.com:2376</serverUrl>
        <apiVersion>1.25</apiVersion>
        <credentialsId>278d46c1-7ecc-4abf-9df0-bbc4003cbe16</credentialsId>
        <connectorType>NETTY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>

+++++++++++++++++++++++++++++++++++++++++++++++

def client = Jenkins.instance.getCloud("DBSSLAVE").getClient()
containers = client.listContainersCmd().exec().each(){ container -> 
  print(container.getId() + " -> ")
  print(container.getLabels())
 println()
}

println()

>>>>  5b4c2d3e28b57104adb0da4df9ec054b0c0c5dfccf2068776839963534ebaa4a -> null

**Comment by KostyaSha** [comment]
So you have container `5b4c2d3e28b57104adb0da4df9ec054b0c0c5dfccf2068776839963534ebaa4a` that returns null for labels ?

**Comment by ericliboon** [comment]
That's weird, container was showing up and running though you're correct its not showing anything when i do inspect. Thanks @KostyaSha for helping me to understand the issue.

docker ps --all
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
5b4c2d3e28b5        x18gvichub01a.prd.cloudnow.dbs.com/its-dcif-01/jenkins-slave:3.0   "/bin/sh -cxe cat ..."   13 days ago         Up 13 days                              elastic_kalam
0305162f0b14        x18gvichub01a.prd.cloudnow.dbs.com/its-dcif-01/jenkins-slave:2.9   "/bin/sh -cxe cat ..."   9 months ago        Created                                 gracious_fermi


==========================================================

docker inspect 5b4c2d3e28b5
[]
Error: No such object: 5b4c2d3e28b5
