### ISSUE TITLE
Unable to mount volume 

### ISSUE THREAD

**Issue by anandpatil** [KostyaSha/yet-another-docker-plugin#287]
Thanks for the plugin! Very useful so far. Now I am trying to mount the volume in the Volumes under Create Container Settings - /var/run/docker.sock:/var/run/docker.sock. I get the error as below , please let me know if there is open issue or workaround for this. I am on Jenkins ver. 2.204.2
Thanks for your help!!!

**Error in provisioning; template='DockerSlaveTemplate[configVersion=1,maxCapacity=4,id=78863ade-5f75-4870-8e17-43061efbafc0,labelString=docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerIOLauncher@6537d2db,remoteFs=/home/jenkins,mode=EXCLUSIVE,retentionStrategy=hudson.slaves.RetentionStrategy$Always@38bedc55,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@11318f2b[image=docindoc,pullImage=DockerPullImage[pullStrategy=PULL_NEVER,credentialsId=3322405,registriesCreds=<null>,connector=<null>],createContainer=DockerCreateContainer[command=,commands=<null>,entrypoint=<null>,hostname=,dnsHosts=[],volumes=[\var\run\docker.sock:\var\run\docker.sock],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=true,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[],dockerLabels=[],shmSize=0,restartPolicy=DockerContainerRestartPolicy[policyName=NO,maximumRetryCount=0],workdir=,user=],stopContainer=DockerStopContainer[timeout=10,connector=<null>],removeContainer=DockerRemoveContainer[removeVolumes=true,force=false,connector=<null>]],nodeProperties=<null>]' for cloud='docindoc-Plugin'
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.BadRequestException: {"message":"create \\var\\run\\docker.sock: \"\\\\var\\\\run\\\\docker.sock\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"}

	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:93)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:32)**

**Comment by aramman** [comment]
Hello , same working for me. My jenkins version is 2.243

**Comment by anandpatil** [comment]
> Hello , same working for me. My jenkins version is 2.243

Can you share the value that you are adding to the Volumes field?
Appreciate your help!

**Comment by aramman** [comment]
Sure , here is the value and "docker info " output executed from docker container.
![Selection_001](https://user-images.githubusercontent.com/23736312/86569081-f971f100-bf7e-11ea-9a9a-eb047eb62167.png)
![Selection_003](https://user-images.githubusercontent.com/23736312/86569087-fb3bb480-bf7e-11ea-8750-a8ee29635b06.png)

**Comment by anandpatil** [comment]
It is working as expected  & not an issue. Thanks for the plugin & support!!
