### ISSUE TITLE
Error when pulling image on swarm: null

### ISSUE THREAD

**Issue by kyhavlov** [KostyaSha/yet-another-docker-plugin#29]
I think the workaround used in the original plugin didn't get pulled into this fork: https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L353

As a result, image pulling fails when targeting a swarm.

**Comment by KostyaSha** [comment]
Could you describe exact issue? Swarm is docker-java issue :(

**Comment by kyhavlov** [comment]
It's the same issue as jenkinsci/docker-plugin#339 - it looks like swarm gives a different response when pulling images, even on success, which throws the plugin off and gives `Could not pull image: null`. The original plugin had an `Ignore Pull Return (Workaround)` option for this, re-adding that is probably needed since it doesn't look like docker-java fixed the actual problem yet.

**Comment by KostyaSha** [comment]
I thought it was already fixed in docker-java, will look at weekend.

**Comment by KostyaSha** [comment]
@kyhavlov plugin should switch to 3.0 docker-java firstly, started work in #30

**Comment by KostyaSha** [comment]
@kyhavlov latest release is using netty and docker-java 3.0.0 Please try.

p.s. 0.1.0-rc11 will be released today with small fix.

**Comment by KostyaSha** [comment]
Should be fixed. Please try new version.

**Comment by dddicillo** [comment]
Ran into this issue in 0.1.0-rc30. I'm temporarily working around it by setting the pull option to 'Never'

**Comment by KostyaSha** [comment]
I think that because of docker-java where i slowpoke...
