### ISSUE TITLE
Feature request: Container settings... --devices

### ISSUE THREAD

**Issue by kknox** [KostyaSha/yet-another-docker-plugin#32]
Would it be possible to extend "Container settings..." with a field users can specify the [docker run](https://docs.docker.com/engine/reference/run/) **--device=[]** parameter?  

The input field should probably be a string that the user can provide input in the form of "/dev/sda:/dev/xvdc:r"

I have a workaround right now in the form of running my containers as `privileged`, which exposes all devices in the system but also lowers container security.

**Comment by KostyaSha** [comment]
wouldn't be difficult, but only after #30
