### ISSUE TITLE
restore ability specify docker version

### ISSUE THREAD

**Issue by KostyaSha** [KostyaSha/yet-another-docker-plugin#4]
Seems now i know when it will be useful

**Comment by fboudra** [comment]
When is it useful? I add to remove it to get things working in the past.

**Comment by KostyaSha** [comment]
@fboudra for example right now docker 1.12 doesn't accept previous model, so you need set lower docker API version explicitly.

**Comment by KostyaSha** [comment]
Available long time ago, closing.
