### ISSUE TITLE
Can not disable TLSverify 

### ISSUE THREAD

**Issue by harrisonfeng** [KostyaSha/yet-another-docker-plugin#43]
TLSverify is always enabled (checked) even if you manually uncheck it.

**Comment by KostyaSha** [comment]
sorry, will double check. some mess happened with this tlsverify. Have you tried to save config and reload?

**Comment by KostyaSha** [comment]
Please check what was saved in global `config.xml` in cloud section.

**Comment by KostyaSha** [comment]
What version installed?

**Comment by KostyaSha** [comment]
Fixed, should be available in jucies as soon as @bsideup resolves https://github.com/jucies/releases/pull/21
In jenkins main update center would be tomorrow.

**Comment by harrisonfeng** [comment]
@KostyaSha , yes, it's working now. Thanks.

**Comment by KostyaSha** [comment]
Cool, you are welcome!
