### ISSUE TITLE
Can be installed in parallel with "the other Docker plugin"?

### ISSUE THREAD

**Issue by pfalcon** [KostyaSha/yet-another-docker-plugin#52]
It would be nice to get disclosure (in docs/wiki) on subj - whether they can be installed altogether at all, and to what extent can be used in parallel (e.g, how bad an idea to let both plugins to control the same Docker daemon). Thanks.

**Comment by KostyaSha** [comment]
Hi, this plugin doesn't conflict with any other plugin that uses docker-java (all other will conflict between each other).

**Comment by KostyaSha** [comment]
This was mentioned in features, i updated it https://github.com/KostyaSha/yet-another-docker-plugin/wiki/Features

**Comment by pfalcon** [comment]
Thanks for confirming.
