### ISSUE TITLE
0.1.0-rc14 binary from Jenkins update center is built with Java8, which is too new for a stable enterprise instal

### ISSUE THREAD

**Issue by pfalcon** [KostyaSha/yet-another-docker-plugin#56]
We're running a Jenkins install on Ubuntu 14.04, which ships with Java7. Everything works, but when we installed Yet Another Docker Plugin, we got in logs:

java.lang.InstantiationException: java.lang.UnsupportedClassVersionError: com/github/kostyasha/yad/DockerBuildVariableContributor : Unsupported major.minor version 52.0

52.0 corresponds to java8. Our Jenkins install is quite busy, and it's pretty risky endeavor to upgrade system java for the need of just one plugin. Can you please consider building a new release with Java7 (assuming source is compatible/easy fixable). Thanks.

**Comment by KostyaSha** [comment]
Sorry, no. There is no any risks in upgrading from end of life java 7 to java8. 
Duplicates #28

**Comment by pfalcon** [comment]
@KostyaSha : Thanks for the reply and pointing to the previous report which explains that there's a dependency on java8.

I just would like to share some "philosophical" perspective on y-a-d project. I very much feel for your motivation of writing it ("But was unable to continue comfortable development"). I find myself in that position regularly - when it's better to fork/start from scratch rather than deal with an original project/code. I rarely follow that route, because the obvious motivation here would be to make a new project "better" than the old. And that's pretty hard. I kinda hinted that in #51, and let me be explicit this time: y-a-d isn't better than the original docker plugin, actually, it's "worse". For example, out of ~50 plugins we use, it's the only one which suddenly requires java8.

I'm not sure if something should/could come out of this, but responsible way would be to add to README something like: "This plugin cannot replace the original Docker plugin [yet]". And "This plugin requires Java8 (note: current Jenkins releases and most of the plugins requires Java7, you may want to check your version before installing Y-A-D)".

And I understand one good response you could give is "patches welcome", but it's usual checking-and-egg problem: a lot in a lifecycle of project depends on a maintainer (fair disclosure again is the simplest thing you could do).

**Comment by KostyaSha** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-37080

> it's "worse".

I'm not enforcing you to use it. I'm only saying that people may try it and if it would work for them - it should work great. yad also has no build-steps and control steps, so yes, not a real replacement. Again, there is no any issues in using java8 instead java7.

> This plugin requires Java8

https://github.com/KostyaSha/yet-another-docker-plugin/commit/debb2d7e9e9f3c0ca14849ac105947efe6356acd


> And I understand one good response you could give is "patches welcome", but it's usual checking-and-egg problem: a lot in a lifecycle of project depends on a maintainer (fair disclosure again is the simplest thing you could do).

Those who really want to enhance will find the way.

#51 still thinks where better to place docs. Maybe `/docs/` dir will win.
