### ISSUE TITLE
env variable DOCKER_XXX not available in pipeline script

### ISSUE THREAD

**Issue by mytliulei** [KostyaSha/yet-another-docker-plugin#61]
pipeline script:
```groovy
node("test") {
  stage 'execute robot test cases'
  sh "export"
  echo "${env.DOCKER_CONTAINER_ID}"
}
```
console output:
```
[Pipeline] sh
[abc] Running shell script
+ export
export BUILD_DISPLAY_NAME='#18'
export BUILD_ID='18'
export BUILD_NUMBER='18'
export BUILD_TAG='jenkins-abc-18'
export BUILD_URL='http://10.18.67.48:8000/job/abc/18/'
export EXECUTOR_NUMBER='0'
export HOME='/home/jenkins'
export HUDSON_COOKIE='4adaf6a1-1c7e-4c9d-86db-d5fb15ddac3f'
export HUDSON_HOME='/var/jenkins_home'
export HUDSON_SERVER_COOKIE='d3f1a8628256127e'
export HUDSON_URL='http://10.18.67.48:8000/'
export JENKINS_HOME='/var/jenkins_home'
export JENKINS_SERVER_COOKIE='durable-75856e1293359a7a00e531e58e5e39b6'
export JENKINS_URL='http://10.18.67.48:8000/'
export JOB_BASE_NAME='abc'
export JOB_NAME='abc'
export JOB_URL='http://10.18.67.48:8000/job/abc/'
export LANG='C.UTF-8'
export LANGUAGE='en_US:en'
export LC_ALL='C.UTF-8'
export LOGNAME='jenkins'
export MAIL='/var/mail/jenkins'
export NODE_NAME='RF-HOST1-26d4e0f2827d'
export OLDPWD='/home/jenkins'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
export PWD='/home/jenkins/workspace/abc'
export SHELL='/bin/bash'
export SHLVL='1'
export SSH_CLIENT='172.17.0.1 50854 22'
export SSH_CONNECTION='172.17.0.1 50854 172.17.0.3 22'
export _='/usr/bin/java'
[Pipeline] echo
null
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Comment by KostyaSha** [comment]
They are injected by environmentContributor

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/DockerBuildVariableContributor.java#L26
Right it uses AbstractBuild, will try think how to use Job type.

**Comment by KostyaSha** [comment]
#62 let's check whether it works

**Comment by KostyaSha** [comment]
Resolved via #62

**Comment by KostyaSha** [comment]
Released

**Comment by mytliulei** [comment]
oh, i update to  0.1.0-rc18, but my pipeline job not work, need special config?
pipeline output, DOCKER_XXX not in env
```
Started by user admin
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
Running on RF-HOST1-5bf30fc46782 in /home/jenkins/workspace/admin/eee
[Pipeline] {
[Pipeline] stage (环境变量)
Entering stage 环境变量
Proceeding
[Pipeline] sh
[eee] Running shell script
+ export
export BUILD_DISPLAY_NAME='#1'
export BUILD_ID='1'
export BUILD_NUMBER='1'
export BUILD_TAG='jenkins-admin-eee-1'
export BUILD_URL='http://10.18.67.48:8000/job/admin/job/eee/1/'
export EXECUTOR_NUMBER='0'
export HOME='/home/jenkins'
export HUDSON_COOKIE='26fcc18c-93bf-4881-ad49-aa9332c19d85'
export HUDSON_HOME='/var/jenkins_home'
export HUDSON_SERVER_COOKIE='d3f1a8628256127e'
export HUDSON_URL='http://10.18.67.48:8000/'
export JENKINS_HOME='/var/jenkins_home'
export JENKINS_SERVER_COOKIE='durable-2b86087b96c9a80603b800e1640139c1'
export JENKINS_URL='http://10.18.67.48:8000/'
export JOB_BASE_NAME='eee'
export JOB_NAME='admin/eee'
export JOB_URL='http://10.18.67.48:8000/job/admin/job/eee/'
export LANG='C.UTF-8'
export LANGUAGE='en_US:en'
export LC_ALL='C.UTF-8'
export LOGNAME='jenkins'
export MAIL='/var/mail/jenkins'
export NODE_NAME='RF-HOST1-5bf30fc46782'
export OLDPWD='/home/jenkins'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
export PWD='/home/jenkins/workspace/admin/eee'
export SHELL='/bin/bash'
export SHLVL='1'
export SSH_CLIENT='172.17.0.1 47471 22'
export SSH_CONNECTION='172.17.0.1 47471 172.17.0.3 22'
export TZ='Asia/Shanghai'
export USER='jenkins'
export _='/usr/bin/java'
... ...
```

freeStyleJob output:
```
Started by user admin
[EnvInject] - Loading node environment variables.
Building remotely on RF-HOST1-e2548d31b02a (robot) in workspace /home/jenkins/workspace/test-dsl
[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
[YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
[YAD-PLUGIN] DOCKER_HOST variable.
Checking out a fresh workspace because there's no workspace at /home/jenkins/workspace/test-dsl
Cleaning local Directory .
Checking out https://192.168.6.58/svn/Version/RF/jenkins/DSL/ at revision '2016-08-16T16:59:30.912 +0800'
A         JobFactory.groovy
At revision 1026

No changes for https://192.168.6.58/svn/Version/RF/jenkins/DSL/TestCaseJob since the previous build
[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
[YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
[YAD-PLUGIN] DOCKER_HOST variable.
[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.
[YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.
[YAD-PLUGIN] DOCKER_HOST variable.
... ...
```

**Comment by KostyaSha** [comment]
that strange...

**Comment by KostyaSha** [comment]
Maybe `        final Executor executor = run.getExecutor();` doesn't return executor for workflowrun. 
Could you debug (if you have java skill)?

**Comment by KostyaSha** [comment]
Bug? https://issues.jenkins-ci.org/browse/JENKINS-33511 
cc @abayer

**Comment by KostyaSha** [comment]
@mytliulei would you be able to parse JSON in pipeline code? I will create special DSL method then.

**Comment by oleg-nenashev** [comment]
@KostyaSha Likely run.getExecutor() does not behave as you expect. Pipeline has fly-weight executors, and they are not guaranteed to run on the same node as the node from the node() command

**Comment by KostyaSha** [comment]
@oleg-nenashev env call happens in node scope, EnvironmentContributor must be called in this scope.

**Comment by oleg-nenashev** [comment]
Yes, env() is supposed to work correctly. But I doubt it takes the workspace information from the execution. Not 100% sure

**Comment by KostyaSha** [comment]
Calling @jglick that suggested to use `EnvironmentContributor`

**Comment by KostyaSha** [comment]
`[16:26]  <jglick> KostyaSha: `EnvironmentContributor` sets job- and build-wide environment variables and works fine on Pipeline jobs & builds AFAIK. There is nothing in that API that refers to nodes.`

**Comment by KostyaSha** [comment]
Could be reworked via `[16:27]  <danielbeck> KostyaSha http://javadoc.jenkins-ci.org/hudson/slaves/NodeProperty.html#buildEnvVars-hudson.EnvVars-hudson.model.TaskListener-
` as template configuration supports NodeProperties already.

**Comment by KostyaSha** [comment]
Is it still actual?

**Comment by judoole** [comment]
@KostyaSha A bit late to the show here, but I am experiencing this exact issue using **Jenkins ver. 2.30** and **YAD v 0.1.0-rc30** Using
```groovy
node("test") {
  stage 'execute robot test cases'
  echo "${env.DOCKER_CONTAINER_ID}"
}
```

yields only `null`. Is there a workaround that I haven't seen?

**Comment by KostyaSha** [comment]
I can try check whether it possible inject variable via NodeProperty in https://github.com/KostyaSha/yet-another-docker-plugin/pull/105

**Comment by KostyaSha** [comment]
But according to https://github.com/KostyaSha/yet-another-docker-plugin/issues/61#issuecomment-241412886 it should be executed. Pipeline uses so hacked APIs that i forgot with what my research end.

**Comment by judoole** [comment]
@KostyaSha Might be that Pipeline aggressively removes variables? The `[YAD-PLUGIN] DOCKER_HOST variable.` is nowhere to be found in the console output for sure. Found this one funny btw https://github.com/jenkinsci/docker-plugin/pull/450

**Comment by judoole** [comment]
@KostyaSha Okey, found a workaround. Seems like the variations of the Pipeline plugin removes the `DOCKER_HOST` by some means or overrides the YAD-plugin. If I would take a guess I think the [Docker Pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Pipeline+Plugin) is involved in some way.

My workaround was to explicitly add `DOCKER_HOST` as a node environment variable, repeating the `Docker URL`, in the setup for YAD in Jenkins settings

**Comment by Starefossen** [comment]
Same problem... YAD-PLUGIN is not run when for pipelined docker build:

```groovy
node('docker-agent') {
  stage 'Print Debug'
  sh 'env | sort'     
}
```

**Comment by KostyaSha** [comment]
> My workaround was to explicitly add DOCKER_HOST as a node environment variable, repeating the Docker URL, in the setup for YAD in Jenkins settings

Sounds very strange. 


There is WIP that probably will help https://github.com/KostyaSha/yet-another-docker-plugin/pull/105

**Comment by bjoernhaeuser** [comment]
Still having this problem today. A pipeline build (using scripted pipeline) does not have the DOCKER_HOST variable set.

**Comment by KostyaSha** [comment]
Did you enable docker specific properties in node properties?

**Comment by bjoernhaeuser** [comment]
You mean in the pipeline or in the YAD config?

**Comment by bjoernhaeuser** [comment]
Ah, wait, yes.
![screen shot 2018-02-09 at 19 28 14](https://user-images.githubusercontent.com/1449155/36043367-66df61d2-0dcf-11e8-8d1b-9edbbac8be16.png)

**Comment by KostyaSha** [comment]
Well, then workflow has bug for EnvironmentContributor's

**Comment by samrocketman** [comment]
envy is not exported in pipelines by default in my experience.  You must use a `withEnv` wrapper.

**Comment by KostyaSha** [comment]
when you take node() it must resolve NodeEnv contributors. Try fill bug to @jglick if it not happening.

**Comment by bjoernhaeuser** [comment]
Okay. setting the DOCKER_HOST manually works. 

Do you have any hint where these information need to be added or are getting lost in the automatic fashion? With this I could do some debugging work.
