### ISSUE TITLE
Support of Cloud Stats plugin

### ISSUE THREAD

**Issue by neonman63** [KostyaSha/yet-another-docker-plugin#70]
Hello. Do you plan of support for Cloud Stats plugin, as an another docker plugins?

**Comment by KostyaSha** [comment]
Could you provide link?

**Comment by neonman63** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Cloud+Statistics+Plugin
Now, in jenkins startup log:
jenkins_1  | Aug 22, 2016 9:38:07 AM org.jenkinsci.plugins.cloudstats.CloudStatistics getIdFor
jenkins_1  | INFO: No support for cloud-stats-plugin by class com.github.kostyasha.yad.DockerComputer

**Comment by KostyaSha** [comment]
@ogondza is it stable?

**Comment by KostyaSha** [comment]
@olivergondza is it stable?

**Comment by olivergondza** [comment]
I do not expect breaking changes any time soon. Also, I would appreciate if you give it a try so i have feedback from different environment.

**Comment by KostyaSha** [comment]
Could it be optional department?

**Comment by olivergondza** [comment]
It is hard to implement that way is it require you to implement interfaces for computer/node/etc. (see reedme). Why would you want to make that optional?

**Comment by KostyaSha** [comment]
@olivergondza do you have any working reference implementation? Openstack-plugin?

**Comment by olivergondza** [comment]
yes, mainly https://github.com/jenkinsci/openstack-cloud-plugin/pull/71

**Comment by KostyaSha** [comment]
@olivergondza `CloudStatistics.ProvisioningListener provisioningListener = CloudStatistics.ProvisioningListener.get()` please create `static` methods that will be easily import and have readable names i.e. `public static getProvisionerListener()`

**Comment by KostyaSha** [comment]
@olivergondza icon in global settings sucks, need some image with cloud + stat chart!
