### ISSUE TITLE
DOCKER_HOST injected into docker in docker container

### ISSUE THREAD

**Issue by AVVS** [KostyaSha/yet-another-docker-plugin#71]
Hi, how do I remove injected DOCKER_HOST from DIND container? This is supposed to only launch a docker container, but not provide this environment variable inside the container

Could you help me?

**Comment by KostyaSha** [comment]
Try just unset this variables in your scripts.

**Comment by AVVS** [comment]
Well, I did. Tried overwriting it, etc. But plugin injects it too many times across the whole build. I've simply rebuild your plugin and removes this from injected vars and now it all works just fine.

**Comment by KostyaSha** [comment]
> But plugin injects it too many times across the whole build

Hm... may be, because environment contributors may be called from different places... I will think about some checkbox in UI to disable it.

**Comment by KostyaSha** [comment]
Or even it should be just ProjectProperty in job configuration.

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/pull/72

**Comment by KostyaSha** [comment]
Could you try PR? Test case fails, so it may be broken... Will look as soon as find time.

**Comment by KostyaSha** [comment]
#105

**Comment by KostyaSha** [comment]
Now you can remove Node Property in template.
