### ISSUE TITLE
Container instantiated. But job not executed

### ISSUE THREAD

**Issue by vasuems** [KostyaSha/yet-another-docker-plugin#77]
I am using Docker 1.11.0 and yet another docker plugin. Containers are instantiated in the docker host. But the jobs are not executed.

**Comment by KostyaSha** [comment]
Loooogs please

**Comment by vasuems** [comment]
INFO: Jenkins is fully up and running
Sep 05, 2016 9:42:15 PM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '1', for: 'docker' label
Sep 05, 2016 9:42:15 PM com.github.kostyasha.yad.DockerCloud provision
INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'
Sep 05, 2016 9:42:16 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFO: Provisioning 'vjenkins' number '0' on 'docker'; Total containers: '1'
Sep 05, 2016 9:42:16 PM com.github.kostyasha.yad.DockerCloud provisionWithWait
INFO: Trying to run container for vjenkins

**Comment by KostyaSha** [comment]
and that not full log

**Comment by vasuems** [comment]
Here the full log. Stepping plugin installation log entries and some of the log content for brevity. 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, prefix) does not exist

2016-09-05 21:05:29.355 defaults[50627:410670] 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, httpListenAddress) does not exist

2016-09-05 21:05:29.381 defaults[50628:410674] 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, httpsPort) does not exist

2016-09-05 21:05:29.408 defaults[50629:410678] 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, httpsListenAddress) does not exist

2016-09-05 21:05:29.434 defaults[50630:410682] 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, httpsKeyStore) does not exist

2016-09-05 21:05:29.461 defaults[50631:410686] 

The domain/default pair of (/Library/Preferences/org.jenkins-ci, httpsKeyStorePassword) does not exist

JENKINS_HOME=/Users/Shared/Jenkins/Home

Jenkins command line for execution:

/usr/bin/java -Dfile.encoding=UTF-8 -XX:PermSize=256m -XX:MaxPermSize=512m -Xms256m -Xmx512m -Djava.io.tmpdir=/Users/Shared/Jenkins/tmp -jar /Applications/Jenkins/jenkins.war --httpPort=8080

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Running from: /Applications/Jenkins/jenkins.war

webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")

Sep 05, 2016 9:05:30 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Logging initialized @484ms

Sep 05, 2016 9:05:30 PM winstone.Logger logInternal

INFO: Beginning extraction from war file

Sep 05, 2016 9:05:34 PM org.eclipse.jetty.util.log.JavaUtilLog warn

WARNING: Empty contextPath

Sep 05, 2016 9:05:34 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: jetty-9.2.z-SNAPSHOT

Sep 05, 2016 9:05:35 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

Jenkins home directory: /Users/Shared/Jenkins/Home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")

Sep 05, 2016 9:05:36 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started w.@33e01298{/,file:/Users/Shared/Jenkins/Home/war/,AVAILABLE}{/Users/Shared/Jenkins/Home/war}

Sep 05, 2016 9:05:36 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started ServerConnector@4f2613d1{HTTP/1.1}{0.0.0.0:8080}

Sep 05, 2016 9:05:36 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started @7072ms

Sep 05, 2016 9:05:36 PM winstone.Logger logInternal

INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled

Sep 05, 2016 9:05:36 PM jenkins.InitReactorRunner$1 onAttained

INFO: Started initialization

Sep 05, 2016 9:05:36 PM jenkins.InitReactorRunner$1 onAttained

INFO: Listed all plugins

Sep 05, 2016 9:05:37 PM jenkins.InitReactorRunner$1 onAttained

INFO: Jenkins is fully up and running

Sep 05, 2016 9:05:47 PM hudson.model.DownloadService$Downloadable load

INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller

Sep 05, 2016 9:05:50 PM hudson.model.DownloadService$Downloadable load

INFO: Obtained the updated data file for hudson.tools.JDKInstaller

Sep 05, 2016 9:05:50 PM hudson.model.AsyncPeriodicWork$1 run

INFO: Finished Download metadata. 11,498 ms

INFO: Loaded all jobs

Sep 05, 2016 9:32:53 PM jenkins.InitReactorRunner$1 onAttained

INFO: Completed initialization

Sep 05, 2016 9:32:53 PM hudson.PluginManager dynamicLoad

INFO: Plugin docker-commons:1.4.0 dynamically installed

Sep 05, 2016 9:32:53 PM hudson.model.UpdateCenter$DownloadJob run

INFO: Installation successful: Docker Commons Plugin

Sep 05, 2016 9:32:53 PM hudson.model.UpdateCenter$DownloadJob run

INFO: Starting the installation of Yet Another Docker Plugin on behalf of jenkins

Sep 05, 2016 9:32:55 PM hudson.model.UpdateCenter$UpdateCenterConfiguration download

INFO: Downloading Yet Another Docker Plugin

Sep 05, 2016 9:35:20 PM hudson.PluginManager dynamicLoad

INFO: Attempting to dynamic load /Users/Shared/Jenkins/Home/plugins/yet-another-docker-plugin.jpi

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Started initialization

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Listed all plugins

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Prepared all plugins

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Started all plugins

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Augmented all extensions

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Loaded all jobs

Sep 05, 2016 9:35:21 PM jenkins.InitReactorRunner$1 onAttained

INFO: Completed initialization

Sep 05, 2016 9:35:21 PM hudson.PluginManager dynamicLoad

INFO: Plugin yet-another-docker-plugin:0.1.0-rc23 dynamically installed

Sep 05, 2016 9:35:21 PM hudson.model.UpdateCenter$DownloadJob run

INFO: Installation successful: Yet Another Docker Plugin

Sep 05, 2016 9:37:57 PM hudson.model.UpdateCenter doSafeRestart

INFO: Scheduling Jenkins reboot

Sep 05, 2016 9:37:57 PM jenkins.model.Jenkins$26 run

INFO: Restart in 10 seconds

Sep 05, 2016 9:38:07 PM jenkins.model.Jenkins$26 run

SEVERE: Restarting VM as requested by anonymous

Sep 05, 2016 9:38:07 PM jenkins.model.Jenkins cleanUp

INFO: Stopping Jenkins

Sep 05, 2016 9:38:07 PM jenkins.model.Jenkins$21 onAttained

INFO: Started termination

Sep 05, 2016 9:38:07 PM jenkins.model.Jenkins$21 onAttained

INFO: Completed termination

Sep 05, 2016 9:38:07 PM jenkins.model.Jenkins _cleanUpDisconnectComputers

INFO: Starting node disconnection

Sep 05, 2016 9:38:08 PM jenkins.model.Jenkins _cleanUpShutdownPluginManager

INFO: Stopping plugin manager

Sep 05, 2016 9:38:08 PM jenkins.model.Jenkins _cleanUpPersistQueue

INFO: Persisting build queue

Sep 05, 2016 9:38:08 PM jenkins.model.Jenkins _cleanUpAwaitDisconnects

INFO: Waiting for node disconnection completion

Sep 05, 2016 9:38:08 PM jenkins.model.Jenkins cleanUp

INFO: Jenkins stopped

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Running from: /Applications/Jenkins/jenkins.war

webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")

Sep 05, 2016 9:38:09 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Logging initialized @311ms

Sep 05, 2016 9:38:09 PM winstone.Logger logInternal

INFO: Beginning extraction from war file

Sep 05, 2016 9:38:09 PM org.eclipse.jetty.util.log.JavaUtilLog warn

WARNING: Empty contextPath

Sep 05, 2016 9:38:09 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: jetty-9.2.z-SNAPSHOT

Sep 05, 2016 9:38:09 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

Jenkins home directory: /Users/Shared/Jenkins/Home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")

Sep 05, 2016 9:38:10 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started w.@117159c0{/,file:/Users/Shared/Jenkins/Home/war/,AVAILABLE}{/Users/Shared/Jenkins/Home/war}

Sep 05, 2016 9:38:11 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started ServerConnector@d737b89{HTTP/1.1}{0.0.0.0:8080}

Sep 05, 2016 9:38:11 PM org.eclipse.jetty.util.log.JavaUtilLog info

INFO: Started @1981ms

Sep 05, 2016 9:38:11 PM winstone.Logger logInternal

INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled

Sep 05, 2016 9:38:11 PM jenkins.InitReactorRunner$1 onAttained

INFO: Started initialization

Sep 05, 2016 9:38:11 PM jenkins.InitReactorRunner$1 onAttained

INFO: Listed all plugins

Sep 05, 2016 9:38:11 PM jenkins.bouncycastle.api.SecurityProviderInitializer addSecurityProvider

INFO: Initializing Bouncy Castle security provider.

Sep 05, 2016 9:38:11 PM jenkins.bouncycastle.api.SecurityProviderInitializer addSecurityProvider

INFO: Bouncy Castle security provider initialized.

Sep 05, 2016 9:38:14 PM jenkins.InitReactorRunner$1 onAttained

INFO: Prepared all plugins

Sep 05, 2016 9:38:14 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error

INFO: Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping

Sep 05, 2016 9:38:15 PM jenkins.InitReactorRunner$1 onAttained

INFO: Started all plugins

Sep 05, 2016 9:38:15 PM jenkins.InitReactorRunner$1 onAttained

INFO: Augmented all extensions

Sep 05, 2016 9:38:15 PM jenkins.InitReactorRunner$1 onAttained

INFO: Loaded all jobs

Sep 05, 2016 9:38:15 PM hudson.model.AsyncPeriodicWork$1 run

INFO: Started Download metadata

Sep 05, 2016 9:38:15 PM hudson.model.AsyncPeriodicWork$1 run

INFO: Finished Download metadata. 5 ms

Sep 05, 2016 9:38:15 PM org.jenkinsci.main.modules.sshd.SSHD start

INFO: Started SSHD at port 51195

Sep 05, 2016 9:38:15 PM jenkins.InitReactorRunner$1 onAttained

INFO: Completed initialization

Sep 05, 2016 9:38:15 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh

INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@72397730: display name [Root WebApplicationContext]; startup date [Mon Sep 05 21:38:15 IST 2016]; root of context hierarchy

Sep 05, 2016 9:38:15 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory

INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@72397730]: org.springframework.beans.factory.support.DefaultListableBeanFactory@3ecf9e8e

Sep 05, 2016 9:38:15 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons

INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3ecf9e8e: defining beans [authenticationManager]; root of factory hierarchy

Sep 05, 2016 9:38:16 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh

INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@5dfc5908: display name [Root WebApplicationContext]; startup date [Mon Sep 05 21:38:16 IST 2016]; root of context hierarchy

Sep 05, 2016 9:38:16 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory

INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@5dfc5908]: org.springframework.beans.factory.support.DefaultListableBeanFactory@22950c2a

Sep 05, 2016 9:38:16 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons

INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@22950c2a: defining beans [filter,legacy]; root of factory hierarchy

Sep 05, 2016 9:38:16 PM hudson.UDPBroadcastThread run

INFO: Cannot listen to UDP port 33,848, skipping: java.net.SocketException: Can't assign requested address

Sep 05, 2016 9:38:16 PM hudson.WebAppMain$3 run

INFO: Jenkins is fully up and running

Sep 05, 2016 9:42:15 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:42:15 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:42:16 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Provisioning 'vjenkins' number '0' on 'docker'; Total containers: '1'

Sep 05, 2016 9:42:16 PM com.github.kostyasha.yad.DockerCloud provisionWithWait

INFO: Trying to run container for vjenkins

Sep 05, 2016 9:42:25 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:42:25 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:42:26 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Provisioning 'vjenkins' number '2' on 'docker'; Total containers: '3'

Sep 05, 2016 9:42:26 PM com.github.kostyasha.yad.DockerCloud provisionWithWait

INFO: Trying to run container for vjenkins

Sep 05, 2016 9:42:35 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:42:35 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:42:36 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Provisioning 'vjenkins' number '4' on 'docker'; Total containers: '5'

Sep 05, 2016 9:42:36 PM com.github.kostyasha.yad.DockerCloud provisionWithWait

INFO: Trying to run container for vjenkins

Sep 05, 2016 9:42:45 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:42:45 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:42:46 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Provisioning 'vjenkins' number '6' on 'docker'; Total containers: '7'

Sep 05, 2016 9:42:46 PM com.github.kostyasha.yad.DockerCloud provisionWithWait

INFO: Trying to run container for vjenkins

Sep 05, 2016 9:42:55 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:42:55 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:42:56 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Provisioning 'vjenkins' number '8' on 'docker'; Total containers: '9'

Sep 05, 2016 9:42:56 PM com.github.kostyasha.yad.DockerCloud provisionWithWait

INFO: Trying to run container for vjenkins

Sep 05, 2016 9:43:05 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Asked to provision load: '1', for: 'docker' label

Sep 05, 2016 9:43:05 PM com.github.kostyasha.yad.DockerCloud provision

INFO: Will provision 'vjenkins', for label: 'docker', in cloud: 'docker'

Sep 05, 2016 9:43:06 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave

INFO: Not Provisioning 'vjenkins'. Instance limit of '10' reached on server 'docker'

**Comment by KostyaSha** [comment]
Strange, i see no useful logging. Is it from "Manage jenkins" -> "System log" ?

**Comment by vasuems** [comment]
This is from the Jenkins.log which is shown in the Manage Jenkins System Log.

**Comment by vasuems** [comment]
I am able to connect to the instance created from the image through normal jenkins slave node mode with ssh key for the jenkins user.

**Comment by KostyaSha** [comment]
Looks likre regression with DockerCloudRetentionStrategy, fixed in master.
