### ISSUE TITLE
Only one slave can be provisioned

### ISSUE THREAD

**Issue by ringtail** [KostyaSha/yet-another-docker-plugin#83]
Hi,the plugin can not provision more than one slave.

**Comment by ringtail** [comment]
![6261607ed667c4508b8d92cff055e93e png](https://cloud.githubusercontent.com/assets/3116693/18499111/894ea412-7a6e-11e6-8819-3b11bdc7aeff.jpeg)

**Comment by ringtail** [comment]
![00a0dc58f4467c9207ccfb13cf46b5e6 png](https://cloud.githubusercontent.com/assets/3116693/18499216/6e30c4f2-7a6f-11e6-85d2-7a9a29278d55.jpeg)

**Comment by KostyaSha** [comment]
Hi, could you post provisioning log?

**Comment by KostyaSha** [comment]
And configuration of Retention strategy + executors.

**Comment by ringtail** [comment]
![20b6c23f5a8ab352c303a62aa9364395 png](https://cloud.githubusercontent.com/assets/3116693/18621205/81d2c0f0-7e52-11e6-9988-861c05964497.jpeg)
![ad8c256df08b38d57972006b6c783d3f png](https://cloud.githubusercontent.com/assets/3116693/18621207/83f5e3ee-7e52-11e6-9926-c56e5439c168.jpeg)

**Comment by ringtail** [comment]
@KostyaSha Any idea?

**Comment by KostyaSha** [comment]
Now I see, you are housing experimental availability it was bug in logic
that it were working before. If it worked fine before, then I can whitelist
it back.
On 21 Sep 2016 4:53 a.m., "莫源" <notifications@github.com> wrote:

> <https://github.com/KostyaSha>

> @KostyaSha <https://github.com/KostyaSha> Any idea?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/KostyaSha/yet-another-docker-plugin/issues/83#issuecomment-248488685>,
or mute the thread

**Comment by KostyaSha** [comment]
@ringtail would you be able to test change?

**Comment by KostyaSha** [comment]
@ringtail please try new version

**Comment by ringtail** [comment]
OK,I'll check it
