### ISSUE TITLE
Forget cloud strategy timeout after jenkins restart

### ISSUE THREAD

**Issue by Reonaydo** [KostyaSha/yet-another-docker-plugin#87]
Hello!
After jenkins` restart plugin(or jenkins itself) forget timeout for cloud retention strategy and it removes containers immediately after first use. This fixed by pressing "Apply" for current jenkins settings.

**Comment by KostyaSha** [comment]
How did you found that it changed? Is it visible in xml?

**Comment by Reonaydo** [comment]
No in xml settings are present
```
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerCloudRetentionStrategy">
            <idleMinutes>90</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerCloudRetentionStrategy">90</idleMinutes>
          </retentionStrategy>
```
And config file does not changed since backup
```
root@ci:~# diff -u /tmp/config.xml /root/.jenkins/config.xml 
root@ci:~# 
```
But containers are removed immediately after log until I pressed "apply". It is strange and I don`t know wich bug is it(plugin, jenkins or some another plugin)

Here log example filtered by container ID
```
root@ci:~# grep -B1 efd5f5db9649 /var/log/jenkins/jenkins.log
[09/20/16 19:42:57] SSH Launch of dev6-efd5f5db9649 on 172.31.240.200 completed in 2,640 ms
--
Sep 20, 2016 7:43:33 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting dev6-efd5f5db9649
Sep 20, 2016 7:43:33 PM com.github.kostyasha.yad.DockerSlave _terminate
INFO: Requesting disconnect for computer: 'dev6-efd5f5db9649'
Sep 20, 2016 7:43:33 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel dev6-efd5f5db9649
--
Sep 20, 2016 7:43:34 PM com.github.kostyasha.yad.DockerSlave _terminate
INFO: Stopped container efd5f5db964963595b1aadeab1bdf37a43ae5010eda358310f4e1a1aeb61c824
Sep 20, 2016 7:43:34 PM com.github.kostyasha.yad.DockerSlave _terminate
INFO: Removed container efd5f5db964963595b1aadeab1bdf37a43ae5010eda358310f4e1a1aeb61c824
--
Sep 20, 2016 7:43:34 PM hudson.slaves.SlaveComputer tryReconnect
INFO: Attempting to reconnect dev6-efd5f5db9649
root@ci:~# 
```

**Comment by KostyaSha** [comment]
SSHLauncher has also timeouts...

**Comment by KostyaSha** [comment]
Sep 20, 2016 7:43:33 PM hudson.slaves.CloudRetentionStrategy check
That not right retention strategy that should be used...

**Comment by Reonaydo** [comment]
Hmm... In selectbox there are two strategy with name "Experimental: Docker Cloud Retention Strategy"

After "Apply"  in logs same name but works ok
```
[09/20/16 20:32:17] SSH Launch of dev6-be3169a7d73e on 172.31.240.200 completed in 2,641 ms
--
Sep 20, 2016 9:04:30 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting dev6-be3169a7d73e
Sep 20, 2016 9:04:30 PM com.github.kostyasha.yad.DockerSlave _terminate
INFO: Requesting disconnect for computer: 'dev6-be3169a7d73e'
Sep 20, 2016 9:04:30 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel dev6-be3169a7d73e
```
About 30 minutes as should be(I have 90 and 30 minutes timeout for different images)

**Comment by KostyaSha** [comment]
TODO add more logging! :)

**Comment by KostyaSha** [comment]
Right,  "Experimental: Docker Cloud Retention Strategy" is standard CloudRetentionStrategy
Is there any reason why 'docker once retention strategy' isn't suitable?

**Comment by Reonaydo** [comment]
I want to reuse containers. It is simply faster. In help of once retention strategy I didn`t see same behavior

**Comment by KostyaSha** [comment]
Interesting whether it work if Once will have configurable counter for allowed slave runs. I.e. destroy every  1 or 2 or 4 builds. Though how to make infinite for int will be the question :)

**Comment by KostyaSha** [comment]
Ok, so to test `CloudRetentionStrategy` `@LocalData` test should be created, then `JenkinsRule` will start fresh jenkins and try check loaded value.

**Comment by KostyaSha** [comment]
Reproduced...

**Comment by KostyaSha** [comment]
X-stream bug, will provide workaround. Also what jenkins version do you use?

**Comment by KostyaSha** [comment]
Workaround in PR, bug initially goes to x-stream library.

**Comment by Reonaydo** [comment]
> Also what jenkins version do you use?

2.19

**Comment by KostyaSha** [comment]
How much strategies do you see for dumb slave now?

**Comment by Reonaydo** [comment]
For dumb slave: 5.
For docker template: 7

**Comment by Reonaydo** [comment]
Thank you!

**Comment by KostyaSha** [comment]
Released, please try.

**Comment by Reonaydo** [comment]
Hmm. Something broken(I tryed 0.1.0-rc26). Containers are created but jenkins does not try reconnect them after first fail

**Comment by KostyaSha** [comment]
Could you show some log?

**Comment by Reonaydo** [comment]
```
Oct 03, 2016 1:54:55 PM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to 172.31.240.200:33756 (try 1/60) - There was a problem while connecting to 172.31.240.200:33756
Oct 03, 2016 1:54:55 PM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to 172.31.240.200:33757 (try 1/60) - There was a problem while connecting to 172.31.240.200:33757
Oct 03, 2016 1:54:57 PM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
INFO: SSH port is open on 172.31.240.200:33756
Oct 03, 2016 1:54:57 PM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for '172.31.240.200:33756'
Oct 03, 2016 1:54:57 PM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
INFO: SSH port is open on 172.31.240.200:33757
Oct 03, 2016 1:54:57 PM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for '172.31.240.200:33757'
Oct 03, 2016 1:55:04 PM hudson.slaves.NodeProvisioner$2 run
INFO: centos-7 provisioning successfully completed. We have now 43 computer(s)
```

**Comment by KostyaSha** [comment]
Looks good, try `1/60` means that it checks TCP port, when open check SSH port and then create SSHLauncher to start.

**Comment by Reonaydo** [comment]
Yes but it does not launch agent anytime. I downgraded plugin to rc24 and all start working
rc24 log example:
> Oct 03, 2016 2:08:37 PM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
> INFO: Creating slave SSH launcher for '172.31.240.200:33761'
> [10/03/16 14:08:37] SSH Launch of dev6-3469d84ba5aa on 172.31.240.200 completed in 2,874 ms

rc26 log:
> Oct 03, 2016 1:54:57 PM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
> INFO: Creating slave SSH launcher for '172.31.240.200:33757'
> Oct 03, 2016 1:55:04 PM hudson.slaves.NodeProvisioner$2 run
> INFO: centos-7 provisioning successfully completed. We have now 43 computer(s)

**Comment by KostyaSha** [comment]
Time for integration test...

**Comment by Reonaydo** [comment]
So. What is the result?

**Comment by KostyaSha** [comment]
Can't reproduce...

**Comment by KostyaSha** [comment]
`INFO: centos-7 provisioning successfully completed. We have now 43 computer(s)`

Was they are provisioned already or did it provision and stop?

Could you show `/threadDump`?

**Comment by KostyaSha** [comment]
Maybe issue in RetentionStrategy...

**Comment by KostyaSha** [comment]
Found, fix merged.
