### ISSUE TITLE
SSL issue with swarm

### ISSUE THREAD

**Issue by clarsonneur** [KostyaSha/yet-another-docker-plugin#97]
Hi,

First of all, thank you for this project! It is really a great news to see this plugin activity.

Currently, I have some trouble with the plugin, when I try to use it against a swarm cluster. (UCP)

my docker client uses the SSL certificate to communicate with swarm. And it is working fine.
But when I try to add those certificate to the plugin and simply do a test connection, I got the following error:

> Oct 06, 2016 3:58:08 PM com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError
> SEVERE: Error during callback
> com.github.kostyasha.yad_docker_java.io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
>         at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
>         at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
>         at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>         at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
>         at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
>         at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
>         at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
>         at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
>         ... 16 more
> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>         at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
>         at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
>         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
>         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
>         at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
>         at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
>         at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
>         at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
>         at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1120)
>         at com.github.kostyasha.yad_docker_java.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1005)
>         ... 18 more
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
>         at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
>         at sun.security.validator.Validator.validate(Validator.java:260)
>         at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
>         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
>         at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
>         ... 26 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
>         at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
>         at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
>         at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
>         ... 32 more
> 

On the jenkins configuration side, after pressing on the test button, nothing is happening. It stays in "testing connection"

I tried using netty and jersey.

The main difference is that jersey complains immediately on the configuration page.

Another note: 
3 or 4 weeks ago, I was able to make work. But I cannot reproduce it...

Do you know if this issue is a known concern?
Any ideas how I can fix it and help to fix it if needed in the plugin?

Thank you

**Comment by KostyaSha** [comment]
How much certs do you have in one cert file?

**Comment by clarsonneur** [comment]
I have 2 certs in ca and certs

You believe it can explain the issue?

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/issues/13#issuecomment-231892106
UCP costs money so when it bit difficult to simulate and test it. But when i installed trial i found that it dumps passwords for all docker nodes in sinctl cert and afaik code expects to have only one cert. I can guess that you will have working connection if you place the first cert that matches to this swarm node.

**Comment by clarsonneur** [comment]
ok

**Comment by clarsonneur** [comment]
I will make a try.

**Comment by clarsonneur** [comment]
I believe you are right. now it works. 

But the strange thing around that is how I were able to make it work recently with this kind of certificates... I have an idea about that...  checking...

**Comment by clarsonneur** [comment]
So, I confirm. the issue was coming from those 2 different certificates. Previously, I believe I was lucky, as the test were successful because the first certificate in each files are valid. 

In my case, the second certificate are invalid. So, if I re-organize to put valid one at first place, it works. else it fails.

I guess this is more likely a UCP concern. So I'm closing the issue. Thank you.

**Comment by KostyaSha** [comment]
I hope it would be possible extract multiple certs, but i stuck with test case and fix... UCP adds the same number of certs as number of nodes. If you can find something in this field, please share.
