### ISSUE TITLE
Having an option to add --no-check-certificate to wget

### ISSUE THREAD

**Issue by clarsonneur** [KostyaSha/yet-another-docker-plugin#98]
Hi,

For testing purpose, we got jenkins over https, but is self certificate. So, not recognized by certs chains.

When the jenkins slave container is started, I got this:

++ command -v wget
+ [[ -x /usr/bin/wget ]]
+ wget https://myserver.example.com//jnlpJars/slave.jar -O slave.jar
--2016-10-07 09:43:56--  https://myserver.example.com//jnlpJars/slave.jar
Resolving larsonsh_jenkins-hpe4it.app.ucp-dev.g4ihos.itcs.hpecorp.net... 16.85.1.94
Connecting to larsonsh_jenkins-hpe4it.app.ucp-dev.g4ihos.itcs.hpecorp.net|16.85.1.94|:443... connected.
ERROR: cannot verify myserver.example.com's certificate, issued by 'CN=MyCompany Private SSL CA,OU=Infrastructure Services,O=My Company,C=US':
  Unable to locally verify the issuer's authority.
ERROR: no certificate subject alternative name matches
        requested host name 'myserver.example.com'.
To connect to myserver.example.com insecurely, use `--no-check-certificate'.

I did not find a way to add this from the plugin configuration page...

So, how could we accept insecure connection if we want that?

**Comment by KostyaSha** [comment]
Needs add option in JNLPLauncher.

**Comment by KostyaSha** [comment]
or even expose slaveArgs.

**Comment by KostyaSha** [comment]
It would make sense to add java_opts and slave_args into config

**Comment by clarsonneur** [comment]
yep. I agree.

**Comment by KostyaSha** [comment]
Could you try change?
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/config.groovy

and add help files to https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/

**Comment by clarsonneur** [comment]
Yep. I will do so.

I found where to update as well. Thank you for your suggestion and help. I will do the PR shortly.

**Comment by clarsonneur** [comment]
Hi, 

I have created some fixes that globally seems to work. But I have a doubt on one piece...

We talked about adding Java Options and JNLP Options to the config. Which is fine.
But the DockerComputerJNLPLauncher.java refer to an [object JNLPLauncher](https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java#L59).

This one is already having
  2 public fields already exposed to the ui and especially a [JVM Options called 'vmargs'](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/JNLPLauncher.java#L61).

My trouble is that JVM Options should be in double with JAVA_OPTIONS that we talked in this issue.
So, My guess is that I should use JNLPLauncher.vmargs instead of creating a new one.

The thing is that I do not know if jenkins deals directly with this JNLPLauncher object.  But I don't think so. Am I assuming correctly?

I believe we need to add those 2 differents data in the config file as well. Your thougts?

**Comment by KostyaSha** [comment]
Good catch, i wrapped it to have class and UI, but this 2 fields could be moved directly to class and UI file and tunnel need to be adjusted also in properties. Replace it with ` protected transient JNLPLauncher jnlpLauncher;`

**Comment by clarsonneur** [comment]
ok. let me check that.

**Comment by clarsonneur** [comment]
ok. So, you mean that we need to create those 2 differents variables, ie vmargs and tunnel to the DockerComputerJNLPLauncher. 

If we set `transient` on `jnlpLauncher`, so we don't care about the data in it. Do we still need it in the class, then?

I thought if we want to remove it from the ui and expose our own attributes, then, just remove it from ui (groovy) and class could be enough. why uses of transient, then?

**Comment by clarsonneur** [comment]
hummm. I think I got it. It is part of the constructor...

**Comment by KostyaSha** [comment]
Create empty DataBoundConstructor and place DataBoundSetter for every new field.

**Comment by KostyaSha** [comment]
Plus in config.groovy remove f.property() and replace with fields.

**Comment by clarsonneur** [comment]
yep. That's what I'm doing. Thanks.

**Comment by KostyaSha** [comment]
And finally replace tostring and equals and hashCode with ReflectionBuilders :)

**Comment by clarsonneur** [comment]
ok got it
